//! Conversation scenes for every target language except Spanish.
//!
//! Spanish keeps its own set in `crate::spanish::scenes` and is deliberately
//! untouched by this module; the two are structurally identical, and unifying
//! them is a follow-up once the Spanish engine is parameterised by language.
//!
//! GENERATED FILE — do not hand-edit. Content was authored per language against
//! the shared scene skeleton (fixed English metadata, per-language dialogue) and
//! regenerated by tools/scene-authoring. The English fields (`id`, `tutor_role`,
//! `learner_role`, `goal`, and each beat's `goal`) are identical across every
//! language on purpose: they key the tutor's deterministic progression.
//!
//! Content status: machine-authored and checked for structure, register
//! consistency and orthography. NOT yet reviewed by a fluent speaker of each
//! language — see docs/SCENE-AUTHORING.md before making teaching claims.

/// One stage of a scene. `max_turns` matches the Spanish engine's pacing.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Beat {
    pub goal: &'static str,
    pub opener: &'static str,
    pub options: &'static str,
    pub max_turns: usize,
}

/// A role-play situation, four beats long.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Scene {
    pub id: &'static str,
    pub tutor_role: &'static str,
    pub learner_role: &'static str,
    pub goal: &'static str,
    pub beats: [Beat; 4],
    /// Indexed by the tutor's level dial: 0 beginner, 1 intermediate, 2 advanced.
    pub target_structures: [[&'static str; 2]; 3],
    pub filler: &'static str,
}

impl Scene {
    pub fn beat(&self, index: usize) -> &Beat {
        &self.beats[index.min(self.beats.len() - 1)]
    }
    pub fn targets(&self, dial: u8) -> &[&'static str; 2] {
        &self.target_structures[(dial.min(2)) as usize]
    }
}

const fn beat(goal: &'static str, opener: &'static str, options: &'static str) -> Beat {
    Beat { goal, opener, options, max_turns: 3 }
}

/// Scene ids, in the order every language presents them.
pub static SCENE_IDS: [&str; 8] = [
    "ordering_food", "meeting_someone", "school_day", "weekend_plans",
    "shopping", "asking_directions", "hotel_checkin", "planning_party",
];


pub static NORWEGIAN_SCENES: [Scene; 8] = [
    Scene {
        id: "ordering_food",
        tutor_role: "waiter",
        learner_role: "customer",
        goal: "order food and a drink, then ask for the bill",
        filler: "Hmm, la meg se…",
        beats: [
            beat("greet and choose a drink", "Hei! Hva vil du ha å drikke?", "Vann eller brus?"),
            beat("order food; offer a dish", "Vi har pizza og fiskesuppe i dag. Hva har du lyst på?", "Pizza eller fiskesuppe?"),
            beat("ask how the food tastes", "Hvordan smaker maten?", "Veldig godt eller sånn passe?"),
            beat("ask for the bill and finish", "Vil du ha noe mer, eller skal jeg hente regningen?", "Noe mer eller regningen?"),
        ],
        target_structures: [
            ["jeg vil ha + substantiv", "kan jeg få…?"],
            ["jeg vil gjerne ha", "kunne du hente…?"],
            ["conditional politeness", "complaining politely"],
        ],
    },
    Scene {
        id: "meeting_someone",
        tutor_role: "new acquaintance",
        learner_role: "new acquaintance",
        goal: "introduce yourself and find a shared interest",
        filler: "Et øyeblikk…",
        beats: [
            beat("exchange names", "Hei! Hva heter du?", "Heter du Anna, eller noe annet?"),
            beat("say where you live", "Hyggelig! Hvor bor du?", "I Oslo eller et annet sted?"),
            beat("find a shared interest", "Hva liker du å gjøre i fritida?", "Fotball eller musikk?"),
            beat("suggest another conversation", "Skal vi ta en kaffe sammen en dag?", "I morgen eller i helga?"),
        ],
        target_structures: [
            ["jeg heter", "jeg bor i"],
            ["jeg pleier å + infinitiv", "jeg har bodd her i + tid"],
            ["shared interests", "polite invitations"],
        ],
    },
    Scene {
        id: "school_day",
        tutor_role: "classmate",
        learner_role: "student",
        goal: "talk about subjects, a class project and after-school activities",
        filler: "La meg tenke…",
        beats: [
            beat("name a favorite subject", "Hvilket fag liker du best?", "Matte eller norsk?"),
            beat("describe a class", "Hvordan var timen i dag?", "Lett eller vanskelig?"),
            beat("describe a project or activity", "Hva handler prosjektet ditt om?", "Dyr eller verdensrommet?"),
            beat("arrange an after-school activity", "Skal vi gjøre noe etter skolen?", "Spille fotball eller gå på kino?"),
        ],
        target_structures: [
            ["jeg liker + substantiv", "det er + adjektiv"],
            ["jeg synes at…", "vi holder på med"],
            ["explain an opinion", "compare learning experiences"],
        ],
    },
    Scene {
        id: "weekend_plans",
        tutor_role: "friend",
        learner_role: "friend",
        goal: "agree an activity, place and time",
        filler: "Skal vi se…",
        beats: [
            beat("choose an activity", "Hva skal vi gjøre i helga?", "Gå på tur eller gå på kino?"),
            beat("choose a place", "Hvor skal vi dra?", "Til byen eller til hytta?"),
            beat("agree a time", "Når passer det for deg?", "Lørdag eller søndag?"),
            beat("confirm the plan", "Da sier vi lørdag klokka tolv, ikke sant?", "Klokka tolv eller klokka to?"),
        ],
        target_structures: [
            ["skal vi…?", "jeg vil gjerne"],
            ["det passer bra for meg", "hva med å + infinitiv?"],
            ["negotiate alternatives", "hypothetical plans"],
        ],
    },
    Scene {
        id: "shopping",
        tutor_role: "shop assistant",
        learner_role: "customer",
        goal: "choose an item, compare options and buy it",
        filler: "Hmm, la meg se…",
        beats: [
            beat("identify an item", "Hei! Hva leter du etter?", "En genser eller en jakke?"),
            beat("choose size and color", "Hvilken størrelse trenger du, og hvilken farge vil du ha?", "Medium i blått eller i svart?"),
            beat("compare an alternative", "Denne er litt billigere. Vil du prøve den også?", "Denne eller den andre?"),
            beat("ask price and decide", "Den er på tilbud nå. Skal du ta den?", "Kjøpe den eller vente litt?"),
        ],
        target_structures: [
            ["jeg leter etter", "hva koster…?"],
            ["har dere den i + farge/størrelse?", "kan jeg prøve den?"],
            ["compare value", "negotiate politely"],
        ],
    },
    Scene {
        id: "asking_directions",
        tutor_role: "helpful pedestrian",
        learner_role: "visitor",
        goal: "find a destination and check the route",
        filler: "Et øyeblikk…",
        beats: [
            beat("ask for a destination", "Hei! Hvor skal du?", "Til stasjonen eller til torget?"),
            beat("establish a landmark", "Ser du kirka der borte, eller den store butikken?", "Kirka eller butikken?"),
            beat("explain and confirm a route", "Du går rett fram og tar til venstre ved kirka. Er det greit?", "Til venstre eller til høyre?"),
            beat("check understanding and finish", "Skal jeg si det én gang til, eller går det bra?", "Én gang til, eller går det bra?"),
        ],
        target_structures: [
            ["hvor er…?", "unnskyld, kan du hjelpe meg?"],
            ["hvordan kommer jeg til…?", "er det langt herfra?"],
            ["clarify ambiguous directions", "compare routes"],
        ],
    },
    Scene {
        id: "hotel_checkin",
        tutor_role: "hotel receptionist",
        learner_role: "guest",
        goal: "check in, ask about facilities and agree checkout",
        filler: "Skal vi se…",
        beats: [
            beat("greet and confirm reservation", "Hei og velkommen! Har du reservert rom hos oss?", "Reservert, eller trenger du et rom?"),
            beat("choose a room", "Hva slags rom vil du ha?", "Enkeltrom eller dobbeltrom?"),
            beat("ask about facilities", "Vi har frokost og treningsrom. Er det noe du lurer på?", "Frokosten eller treningsrommet?"),
            beat("agree checkout and finish", "Når skal du sjekke ut?", "Klokka ti eller klokka elleve?"),
        ],
        target_structures: [
            ["jeg har bestilt", "er det…?"],
            ["kunne jeg få…?", "når serveres frokosten?"],
            ["request an accommodation", "resolve a reservation problem"],
        ],
    },
    Scene {
        id: "planning_party",
        tutor_role: "friend helping organize",
        learner_role: "party organizer",
        goal: "plan guests, food, activities and timing",
        filler: "La meg tenke…",
        beats: [
            beat("decide who is invited", "Hvem skal vi invitere?", "Bare venner eller familien også?"),
            beat("choose food", "Hva skal vi servere?", "Pizza eller tacos?"),
            beat("choose an activity", "Hva skal vi gjøre på festen?", "Spill eller musikk og dans?"),
            beat("confirm when and finish", "Når skal festen være?", "Fredag eller lørdag?"),
        ],
        target_structures: [
            ["vi inviterer", "vi kan ha + substantiv"],
            ["hva om vi + verb?", "jeg foreslår at vi…"],
            ["coordinate preferences", "negotiate constraints"],
        ],
    },
];

pub static ENGLISH_SCENES: [Scene; 8] = [
    Scene {
        id: "ordering_food",
        tutor_role: "waiter",
        learner_role: "customer",
        goal: "order food and a drink, then ask for the bill",
        filler: "Hmm, let me see…",
        beats: [
            beat("greet and choose a drink", "Hi! What would you like to drink?", "Water or juice?"),
            beat("order food; offer a dish", "We've got pizza and tacos. What would you like to eat?", "Pizza or tacos?"),
            beat("ask how the food tastes", "How's the food?", "Really good, or just okay?"),
            beat("ask for the bill and finish", "Would you like anything else, or shall I bring the bill?", "Anything else, or the bill?"),
        ],
        target_structures: [
            ["I'd like + noun", "Do you have…?"],
            ["Could I have…?", "Could you bring me…?"],
            ["conditional politeness", "complaining politely"],
        ],
    },
    Scene {
        id: "meeting_someone",
        tutor_role: "new acquaintance",
        learner_role: "new acquaintance",
        goal: "introduce yourself and find a shared interest",
        filler: "Just a moment…",
        beats: [
            beat("exchange names", "Hi! What's your name?", "Is it Anna, or something else?"),
            beat("say where you live", "Where do you live?", "In a city or in a small town?"),
            beat("find a shared interest", "What do you like doing in your free time?", "Sports or music?"),
            beat("suggest another conversation", "It was lovely meeting you! Shall we talk again another day?", "Tomorrow or this weekend?"),
        ],
        target_structures: [
            ["my name is", "I like + -ing"],
            ["I usually + verb", "I've been living + for/since"],
            ["shared interests", "polite invitations"],
        ],
    },
    Scene {
        id: "school_day",
        tutor_role: "classmate",
        learner_role: "student",
        goal: "talk about subjects, a class project and after-school activities",
        filler: "Hmm, let me see…",
        beats: [
            beat("name a favorite subject", "What's your favorite subject?", "Science or art?"),
            beat("describe a class", "What do you do in that class?", "Do you read, or do projects?"),
            beat("describe a project or activity", "What project do you want to do?", "A drawing or a model?"),
            beat("arrange an after-school activity", "What do you want to do after school?", "Play a game or just relax?"),
        ],
        target_structures: [
            ["I like + subject", "I have + class"],
            ["Today we + past simple", "I've learned how to…"],
            ["explain an opinion", "compare learning experiences"],
        ],
    },
    Scene {
        id: "weekend_plans",
        tutor_role: "friend",
        learner_role: "friend",
        goal: "agree an activity, place and time",
        filler: "Let me think…",
        beats: [
            beat("choose an activity", "What do you want to do this weekend?", "Go to the park or watch a film?"),
            beat("choose a place", "Where shall we meet?", "At the park or at my place?"),
            beat("agree a time", "What time works for you?", "In the morning or in the afternoon?"),
            beat("confirm the plan", "Great, that's a plan! What shall we bring?", "Some food or a ball?"),
        ],
        target_structures: [
            ["I want to + verb", "at + time"],
            ["I'm going to + verb", "Shall we…?"],
            ["negotiate alternatives", "hypothetical plans"],
        ],
    },
    Scene {
        id: "shopping",
        tutor_role: "shop assistant",
        learner_role: "customer",
        goal: "choose an item, compare options and buy it",
        filler: "Hmm, let me see…",
        beats: [
            beat("identify an item", "Hi! What are you looking for?", "A T-shirt or some shoes?"),
            beat("choose size and color", "What color would you like?", "Blue or red?"),
            beat("compare an alternative", "I've got another one. Would you like to see it?", "This one or the other one?"),
            beat("ask price and decide", "Will you take this one, or would you like to keep looking?", "Buy it, or keep looking?"),
        ],
        target_structures: [
            ["I'd like this one", "How much is…?"],
            ["bigger than / more + adjective + than", "I'm looking for…"],
            ["compare value", "negotiate politely"],
        ],
    },
    Scene {
        id: "asking_directions",
        tutor_role: "helpful pedestrian",
        learner_role: "visitor",
        goal: "find a destination and check the route",
        filler: "Just a moment…",
        beats: [
            beat("ask for a destination", "Hi! Where are you trying to get to?", "The park or the station?"),
            beat("establish a landmark", "Can you see the building across the road?", "The white one or the blue one?"),
            beat("explain and confirm a route", "Go straight ahead and then turn right. What do you do first?", "Go straight or turn?"),
            beat("check understanding and finish", "Do you know how to get there, or shall I say it again?", "All good, or say it again?"),
        ],
        target_structures: [
            ["Where is…?", "on the right / on the left"],
            ["I have to turn…", "How long does it take?"],
            ["clarify ambiguous directions", "compare routes"],
        ],
    },
    Scene {
        id: "hotel_checkin",
        tutor_role: "hotel receptionist",
        learner_role: "guest",
        goal: "check in, ask about facilities and agree checkout",
        filler: "Let me see…",
        beats: [
            beat("greet and confirm reservation", "Welcome! Do you have a reservation?", "With a reservation, or without?"),
            beat("choose a room", "What kind of room do you need?", "A single or a double?"),
            beat("ask about facilities", "What would you like to know about the hotel?", "Breakfast or the pool?"),
            beat("agree checkout and finish", "What time would you like to check out tomorrow?", "Early, or after breakfast?"),
        ],
        target_structures: [
            ["I have a reservation", "Is there…?"],
            ["I'd like to know…", "Is it possible to…?"],
            ["request an accommodation", "resolve a reservation problem"],
        ],
    },
    Scene {
        id: "planning_party",
        tutor_role: "friend helping organize",
        learner_role: "party organizer",
        goal: "plan guests, food, activities and timing",
        filler: "Hmm, let me see…",
        beats: [
            beat("decide who is invited", "Who do you want to invite to the party?", "Family or friends?"),
            beat("choose food", "What are we going to eat?", "Pizza or sandwiches?"),
            beat("choose an activity", "What shall we do at the party?", "Music or games?"),
            beat("confirm when and finish", "Everything's ready! What time does it start?", "Four o'clock or five?"),
        ],
        target_structures: [
            ["I want to invite…", "we're going to eat…"],
            ["I'd like to organize…", "we could + verb"],
            ["coordinate preferences", "negotiate constraints"],
        ],
    },
];

pub static FRENCH_SCENES: [Scene; 8] = [
    Scene {
        id: "ordering_food",
        tutor_role: "waiter",
        learner_role: "customer",
        goal: "order food and a drink, then ask for the bill",
        filler: "Alors, voyons voir…",
        beats: [
            beat("greet and choose a drink", "Bonjour ! Qu'est-ce que vous voulez boire ?", "De l'eau ou un jus ?"),
            beat("order food; offer a dish", "On a des pizzas et des salades. Qu'est-ce que vous voulez manger ?", "Pizza ou salade ?"),
            beat("ask how the food tastes", "Alors, ça vous plaît ?", "C'est bon ou pas ?"),
            beat("ask for the bill and finish", "Vous voulez autre chose, ou je vous apporte l'addition ?", "Autre chose ou l'addition ?"),
        ],
        target_structures: [
            ["je voudrais + nom", "vous avez… ?"],
            ["j'aimerais", "vous pourriez m'apporter… ?"],
            ["conditional politeness", "complaining politely"],
        ],
    },
    Scene {
        id: "meeting_someone",
        tutor_role: "new acquaintance",
        learner_role: "new acquaintance",
        goal: "introduce yourself and find a shared interest",
        filler: "Un instant…",
        beats: [
            beat("exchange names", "Salut ! Tu t'appelles comment ?", "Léa ou un autre prénom ?"),
            beat("say where you live", "Et tu habites où ?", "À Paris ou ailleurs ?"),
            beat("find a shared interest", "Moi, j'adore le cinéma. Et toi, tu aimes quoi, comme loisirs ?", "Le cinéma ou le sport ?"),
            beat("suggest another conversation", "Ça te dirait qu'on se revoie pour discuter ?", "Cette semaine ou le week-end prochain ?"),
        ],
        target_structures: [
            ["je m'appelle", "j'habite à + ville"],
            ["j'ai l'habitude de + infinitif", "ça fait… que j'habite"],
            ["shared interests", "polite invitations"],
        ],
    },
    Scene {
        id: "school_day",
        tutor_role: "classmate",
        learner_role: "student",
        goal: "talk about subjects, a class project and after-school activities",
        filler: "Hmm, attends…",
        beats: [
            beat("name a favorite subject", "Salut ! C'est quoi, ta matière préférée ?", "Les maths ou l'histoire ?"),
            beat("describe a class", "Et le cours de ce matin, c'était comment ?", "Intéressant ou ennuyeux ?"),
            beat("describe a project or activity", "Tu fais quoi comme projet en ce moment ?", "Un exposé ou une expérience ?"),
            beat("arrange an after-school activity", "On fait quelque chose après les cours ?", "Foot ou bibliothèque ?"),
        ],
        target_structures: [
            ["j'aime + article + nom", "le cours est + adjectif"],
            ["je trouve que + phrase", "après les cours, on peut + infinitif"],
            ["explain an opinion", "compare learning experiences"],
        ],
    },
    Scene {
        id: "weekend_plans",
        tutor_role: "friend",
        learner_role: "friend",
        goal: "agree an activity, place and time",
        filler: "Alors, voyons voir…",
        beats: [
            beat("choose an activity", "Tu veux faire quoi ce week-end ?", "Cinéma ou rando ?"),
            beat("choose a place", "On se retrouve où ?", "Chez moi ou en ville ?"),
            beat("agree a time", "Et à quelle heure ?", "Le matin ou l'après-midi ?"),
            beat("confirm the plan", "Donc c'est bon, on fait ça ?", "C'est bon ou on change ?"),
        ],
        target_structures: [
            ["je veux + infinitif", "à + heure"],
            ["ça te dit de + infinitif ?", "si tu veux, on peut…"],
            ["negotiate alternatives", "hypothetical plans"],
        ],
    },
    Scene {
        id: "shopping",
        tutor_role: "shop assistant",
        learner_role: "customer",
        goal: "choose an item, compare options and buy it",
        filler: "Hmm, attendez…",
        beats: [
            beat("identify an item", "Bonjour ! Je peux vous aider ? Vous cherchez quelque chose ?", "Un pull ou un t-shirt ?"),
            beat("choose size and color", "Vous faites quelle taille ? Et en quelle couleur ?", "En bleu ou en noir ?"),
            beat("compare an alternative", "Il y a aussi ce modèle-là. Vous préférez lequel ?", "Celui-ci ou celui-là ?"),
            beat("ask price and decide", "Il n'est pas cher, en plus. Alors, vous le prenez ?", "Vous le prenez ou vous laissez ?"),
        ],
        target_structures: [
            ["je cherche + nom", "ça coûte combien ?"],
            ["celui-ci / celui-là", "je préfère… parce que…"],
            ["compare value", "negotiate politely"],
        ],
    },
    Scene {
        id: "asking_directions",
        tutor_role: "helpful pedestrian",
        learner_role: "visitor",
        goal: "find a destination and check the route",
        filler: "Alors, voyons voir…",
        beats: [
            beat("ask for a destination", "Bonjour ! Vous cherchez quelque chose ?", "La gare ou le musée ?"),
            beat("establish a landmark", "Vous voyez la pharmacie, là-bas ?", "Vous la voyez ou pas ?"),
            beat("explain and confirm a route", "Alors, vous allez tout droit, puis à gauche à la pharmacie. C'est bon ?", "À gauche ou à droite ?"),
            beat("check understanding and finish", "Vous avez compris, ou je répète ?", "C'est clair ou je répète ?"),
        ],
        target_structures: [
            ["où est + article + nom ?", "à gauche / à droite / tout droit"],
            ["pourriez-vous me dire où… ?", "il faut + infinitif"],
            ["clarify ambiguous directions", "compare routes"],
        ],
    },
    Scene {
        id: "hotel_checkin",
        tutor_role: "hotel receptionist",
        learner_role: "guest",
        goal: "check in, ask about facilities and agree checkout",
        filler: "Un instant…",
        beats: [
            beat("greet and confirm reservation", "Bonsoir, bienvenue ! C'est à quel nom, la réservation ?", "Dupont ou un autre nom ?"),
            beat("choose a room", "Vous préférez quelle chambre ?", "Un grand lit ou deux lits ?"),
            beat("ask about facilities", "Vous avez des questions sur l'hôtel ?", "Le wifi ou le petit-déjeuner ?"),
            beat("agree checkout and finish", "Et vous partez quand ?", "Demain matin ou après-demain ?"),
        ],
        target_structures: [
            ["j'ai une réservation", "il y a… ?"],
            ["est-ce qu'il serait possible de… ?", "à quelle heure est + nom ?"],
            ["request an accommodation", "resolve a reservation problem"],
        ],
    },
    Scene {
        id: "planning_party",
        tutor_role: "friend helping organize",
        learner_role: "party organizer",
        goal: "plan guests, food, activities and timing",
        filler: "Hmm, attends…",
        beats: [
            beat("decide who is invited", "Alors, tu invites qui à la fête ?", "Des amis ou la famille ?"),
            beat("choose food", "Et on prépare quoi à manger ?", "Des pizzas ou un buffet ?"),
            beat("choose an activity", "On fait quoi comme animation ?", "De la musique ou des jeux ?"),
            beat("confirm when and finish", "C'est pour quand, alors ?", "Vendredi soir ou samedi ?"),
        ],
        target_structures: [
            ["j'invite + nom", "on mange + nom"],
            ["il faudrait + infinitif", "on pourrait + infinitif"],
            ["coordinate preferences", "negotiate constraints"],
        ],
    },
];

pub static GERMAN_SCENES: [Scene; 8] = [
    Scene {
        id: "ordering_food",
        tutor_role: "waiter",
        learner_role: "customer",
        goal: "order food and a drink, then ask for the bill",
        filler: "Hm, mal sehen…",
        beats: [
            beat("greet and choose a drink", "Guten Tag! Was möchten Sie trinken?", "Wasser oder Saft?"),
            beat("order food; offer a dish", "Wir haben heute Schnitzel und Pizza. Was möchten Sie essen?", "Schnitzel oder Pizza?"),
            beat("ask how the food tastes", "Und, wie schmeckt es Ihnen?", "Gut oder nicht so gut?"),
            beat("ask for the bill and finish", "Möchten Sie noch etwas, oder darf ich die Rechnung bringen?", "Noch etwas oder die Rechnung?"),
        ],
        target_structures: [
            ["ich möchte + Akkusativ", "haben Sie …?"],
            ["ich hätte gern …", "könnten Sie mir … bringen?"],
            ["conditional politeness", "complaining politely"],
        ],
    },
    Scene {
        id: "meeting_someone",
        tutor_role: "new acquaintance",
        learner_role: "new acquaintance",
        goal: "introduce yourself and find a shared interest",
        filler: "Einen Moment…",
        beats: [
            beat("exchange names", "Hallo! Wie heißt du?", "Heißt du Anna oder anders?"),
            beat("say where you live", "Und wo wohnst du?", "In Berlin oder woanders?"),
            beat("find a shared interest", "Was machst du gern in deiner Freizeit?", "Sport oder Musik?"),
            beat("suggest another conversation", "Wollen wir uns mal wieder treffen?", "Morgen oder am Wochenende?"),
        ],
        target_structures: [
            ["ich heiße …", "ich wohne in + Dativ"],
            ["ich interessiere mich für + Akkusativ", "hast du Lust, … zu + Infinitiv?"],
            ["shared interests", "polite invitations"],
        ],
    },
    Scene {
        id: "school_day",
        tutor_role: "classmate",
        learner_role: "student",
        goal: "talk about subjects, a class project and after-school activities",
        filler: "Lass mich überlegen…",
        beats: [
            beat("name a favorite subject", "Was ist dein Lieblingsfach?", "Mathe oder Deutsch?"),
            beat("describe a class", "Wie findest du den Unterricht heute?", "Interessant oder langweilig?"),
            beat("describe a project or activity", "Woran arbeitet ihr gerade im Unterricht?", "Ein Projekt oder ein Referat?"),
            beat("arrange an after-school activity", "Wollen wir nach der Schule etwas zusammen machen?", "Lernen oder Fußball spielen?"),
        ],
        target_structures: [
            ["mein Lieblingsfach ist …", "ich finde … + Adjektiv"],
            ["ich finde, dass … (Nebensatz)", "am liebsten + Verb"],
            ["explain an opinion", "compare learning experiences"],
        ],
    },
    Scene {
        id: "weekend_plans",
        tutor_role: "friend",
        learner_role: "friend",
        goal: "agree an activity, place and time",
        filler: "Hm, mal sehen…",
        beats: [
            beat("choose an activity", "Was wollen wir am Wochenende machen?", "Kino oder Fahrrad fahren?"),
            beat("choose a place", "Und wo treffen wir uns?", "Bei mir oder in der Stadt?"),
            beat("agree a time", "Wann passt es dir?", "Um drei oder um fünf?"),
            beat("confirm the plan", "Also, Samstag in der Stadt – bist du dabei?", "Passt so, oder lieber später?"),
        ],
        target_structures: [
            ["wollen wir …?", "am Samstag / um drei Uhr"],
            ["ich würde lieber …", "hättest du Lust auf + Akkusativ?"],
            ["negotiate alternatives", "hypothetical plans"],
        ],
    },
    Scene {
        id: "shopping",
        tutor_role: "shop assistant",
        learner_role: "customer",
        goal: "choose an item, compare options and buy it",
        filler: "Einen Moment…",
        beats: [
            beat("identify an item", "Guten Tag! Kann ich Ihnen helfen? Was suchen Sie?", "Eine Jacke oder ein T-Shirt?"),
            beat("choose size and color", "Welche Größe und welche Farbe brauchen Sie?", "Blau in M oder schwarz in L?"),
            beat("compare an alternative", "Hier ist noch ein anderes Modell. Welches gefällt Ihnen besser?", "Das erste oder das zweite?"),
            beat("ask price and decide", "Das ist eines unserer beliebtesten Modelle. Haben Sie noch eine Frage dazu?", "Zum Preis oder zur Größe?"),
        ],
        target_structures: [
            ["ich suche + Akkusativ", "was kostet das?"],
            ["ich hätte gern … in Größe M", "das gefällt mir besser als …"],
            ["compare value", "negotiate politely"],
        ],
    },
    Scene {
        id: "asking_directions",
        tutor_role: "helpful pedestrian",
        learner_role: "visitor",
        goal: "find a destination and check the route",
        filler: "Hm, mal sehen…",
        beats: [
            beat("ask for a destination", "Entschuldigung, kann ich Ihnen helfen? Wo möchten Sie hin?", "Zum Bahnhof oder zum Museum?"),
            beat("establish a landmark", "Kennen Sie hier schon etwas, zum Beispiel die Kirche oder den Marktplatz?", "Die Kirche oder den Marktplatz?"),
            beat("explain and confirm a route", "Gehen Sie geradeaus bis zur Kirche und dann links. Gehen Sie lieber zu Fuß oder fahren Sie mit dem Bus?", "Zu Fuß oder mit dem Bus?"),
            beat("check understanding and finish", "Also, wie gehen Sie jetzt?", "Erst geradeaus oder erst links?"),
        ],
        target_structures: [
            ["wo ist …?", "wie komme ich zu + Dativ?"],
            ["könnten Sie mir sagen, wo … ist?", "ich muss … abbiegen (Modalverb)"],
            ["clarify ambiguous directions", "compare routes"],
        ],
    },
    Scene {
        id: "hotel_checkin",
        tutor_role: "hotel receptionist",
        learner_role: "guest",
        goal: "check in, ask about facilities and agree checkout",
        filler: "Einen Moment…",
        beats: [
            beat("greet and confirm reservation", "Guten Abend! Haben Sie eine Reservierung?", "Reserviert oder ohne Reservierung?"),
            beat("choose a room", "Was für ein Zimmer möchten Sie?", "Einzelzimmer oder Doppelzimmer?"),
            beat("ask about facilities", "Haben Sie noch Fragen zum Hotel?", "Zum Frühstück oder zum WLAN?"),
            beat("agree checkout and finish", "Und bis wann möchten Sie bleiben?", "Bis Sonntag oder bis Montag?"),
        ],
        target_structures: [
            ["ich habe eine Reservierung auf den Namen …", "gibt es …?"],
            ["ich hätte gern ein Zimmer mit + Dativ", "wann muss ich auschecken?"],
            ["request an accommodation", "resolve a reservation problem"],
        ],
    },
    Scene {
        id: "planning_party",
        tutor_role: "friend helping organize",
        learner_role: "party organizer",
        goal: "plan guests, food, activities and timing",
        filler: "Lass mich überlegen…",
        beats: [
            beat("decide who is invited", "Wen laden wir alles ein?", "Nur Freunde oder auch Familie?"),
            beat("choose food", "Und was gibt es zu essen?", "Pizza oder Kuchen?"),
            beat("choose an activity", "Was machen wir auf der Party?", "Musik oder Spiele?"),
            beat("confirm when and finish", "Wann soll die Party sein?", "Freitag oder Samstag?"),
        ],
        target_structures: [
            ["wir laden … ein (trennbares Verb)", "es gibt + Akkusativ"],
            ["wir könnten …", "lass uns … (Vorschlag)"],
            ["coordinate preferences", "negotiate constraints"],
        ],
    },
];

pub static ITALIAN_SCENES: [Scene; 8] = [
    Scene {
        id: "ordering_food",
        tutor_role: "waiter",
        learner_role: "customer",
        goal: "order food and a drink, then ask for the bill",
        filler: "Mmm, vediamo…",
        beats: [
            beat("greet and choose a drink", "Buongiorno! Cosa prende da bere?", "Un caffè o un'acqua?"),
            beat("order food; offer a dish", "Abbiamo la pizza e la pasta al pomodoro. Cosa desidera mangiare?", "Pizza o pasta?"),
            beat("ask how the food tastes", "Tutto bene? Le piace?", "Le piace molto o poco?"),
            beat("ask for the bill and finish", "Desidera altro o Le porto il conto?", "Altro o il conto?"),
        ],
        target_structures: [
            ["vorrei + noun", "avete…?"],
            ["mi porta…?", "potrei avere…?"],
            ["conditional politeness", "complaining politely"],
        ],
    },
    Scene {
        id: "meeting_someone",
        tutor_role: "new acquaintance",
        learner_role: "new acquaintance",
        goal: "introduce yourself and find a shared interest",
        filler: "Un attimo…",
        beats: [
            beat("exchange names", "Ciao! Come ti chiami?", "Anna o un altro nome?"),
            beat("say where you live", "Piacere! E dove abiti?", "In città o in campagna?"),
            beat("find a shared interest", "Cosa ti piace fare nel tempo libero?", "Sport o musica?"),
            beat("suggest another conversation", "Che bello! Ci prendiamo un caffè un giorno di questi?", "Domani o la settimana prossima?"),
        ],
        target_structures: [
            ["mi chiamo", "mi piace"],
            ["di solito + verb", "abito qui da + time"],
            ["shared interests", "polite invitations"],
        ],
    },
    Scene {
        id: "school_day",
        tutor_role: "classmate",
        learner_role: "student",
        goal: "talk about subjects, a class project and after-school activities",
        filler: "Fammi pensare…",
        beats: [
            beat("name a favorite subject", "Ciao! Qual è la tua materia preferita?", "Matematica o storia?"),
            beat("describe a class", "Com'è stata la lezione di oggi?", "Facile o difficile?"),
            beat("describe a project or activity", "Cosa fate per il progetto di classe?", "Un poster o una presentazione?"),
            beat("arrange an after-school activity", "Dopo la scuola facciamo qualcosa insieme?", "Studiamo o giochiamo a calcio?"),
        ],
        target_structures: [
            ["mi piace + noun", "è + adjective"],
            ["preferisco… perché…", "secondo me"],
            ["explain an opinion", "compare learning experiences"],
        ],
    },
    Scene {
        id: "weekend_plans",
        tutor_role: "friend",
        learner_role: "friend",
        goal: "agree an activity, place and time",
        filler: "Fammi vedere…",
        beats: [
            beat("choose an activity", "Ciao! Cosa facciamo questo fine settimana?", "Cinema o pizza?"),
            beat("choose a place", "Bene! E dove andiamo?", "In centro o vicino a casa?"),
            beat("agree a time", "A che ora ci vediamo?", "Alle sei o alle otto?"),
            beat("confirm the plan", "Perfetto! Allora è deciso?", "Confermato o cambiamo?"),
        ],
        target_structures: [
            ["andiamo a + place", "alle + hour"],
            ["ti va di + infinitive?", "potremmo + infinitive"],
            ["negotiate alternatives", "hypothetical plans"],
        ],
    },
    Scene {
        id: "shopping",
        tutor_role: "shop assistant",
        learner_role: "customer",
        goal: "choose an item, compare options and buy it",
        filler: "Un attimo…",
        beats: [
            beat("identify an item", "Buongiorno! Posso aiutarla? Cosa cerca?", "Una maglietta o dei pantaloni?"),
            beat("choose size and color", "Che taglia porta? E che colore Le piace?", "Media o grande, blu o rosa?"),
            beat("compare an alternative", "Questo costa un po' di più, ma è di cotone. Preferisce questo o l'altro?", "Questo o l'altro?"),
            beat("ask price and decide", "Allora, ha deciso? Lo prende?", "Lo prende o ci pensa?"),
        ],
        target_structures: [
            ["cerco + noun", "quanto costa?"],
            ["posso provarlo?", "è più… di"],
            ["compare value", "negotiate politely"],
        ],
    },
    Scene {
        id: "asking_directions",
        tutor_role: "helpful pedestrian",
        learner_role: "visitor",
        goal: "find a destination and check the route",
        filler: "Mmm, vediamo…",
        beats: [
            beat("ask for a destination", "Buongiorno! Ha bisogno di aiuto? Dove deve andare?", "Alla stazione o al museo?"),
            beat("establish a landmark", "Vede la chiesa lì in fondo alla strada?", "La vede o no?"),
            beat("explain and confirm a route", "Vada dritto fino alla chiesa e poi giri a sinistra. Ha capito?", "A sinistra o a destra?"),
            beat("check understanding and finish", "Perfetto! Vuole che ripeta o è tutto chiaro?", "Ripeto o è chiaro?"),
        ],
        target_structures: [
            ["dov'è + noun?", "a destra / a sinistra"],
            ["scusi, potrebbe dirmi…?", "quanto ci vuole a piedi?"],
            ["clarify ambiguous directions", "compare routes"],
        ],
    },
    Scene {
        id: "hotel_checkin",
        tutor_role: "hotel receptionist",
        learner_role: "guest",
        goal: "check in, ask about facilities and agree checkout",
        filler: "Un attimo…",
        beats: [
            beat("greet and confirm reservation", "Buonasera! Ha una prenotazione?", "A nome Rossi o un altro nome?"),
            beat("choose a room", "Bene. Che camera preferisce?", "Singola o doppia?"),
            beat("ask about facilities", "Vuole sapere qualcosa sui nostri servizi?", "La colazione o il Wi-Fi?"),
            beat("agree checkout and finish", "Ultima cosa: a che ora pensa di fare il check-out?", "Presto la mattina o verso mezzogiorno?"),
        ],
        target_structures: [
            ["ho una prenotazione", "c'è + noun?"],
            ["è possibile + infinitive?", "a che ora si può…?"],
            ["request an accommodation", "resolve a reservation problem"],
        ],
    },
    Scene {
        id: "planning_party",
        tutor_role: "friend helping organize",
        learner_role: "party organizer",
        goal: "plan guests, food, activities and timing",
        filler: "Fammi pensare…",
        beats: [
            beat("decide who is invited", "Ciao! Allora, chi invitiamo alla festa?", "Solo gli amici o anche la famiglia?"),
            beat("choose food", "E da mangiare cosa prepariamo?", "Pizza o panini?"),
            beat("choose an activity", "Cosa facciamo durante la festa?", "Musica e balli o giochi?"),
            beat("confirm when and finish", "Ultima cosa: quando la facciamo?", "Sabato o domenica?"),
        ],
        target_structures: [
            ["invitiamo + noun", "facciamo + noun"],
            ["preferisco… piuttosto che…", "dovremmo + infinitive"],
            ["coordinate preferences", "negotiate constraints"],
        ],
    },
];

pub static PORTUGUESE_SCENES: [Scene; 8] = [
    Scene {
        id: "ordering_food",
        tutor_role: "waiter",
        learner_role: "customer",
        goal: "order food and a drink, then ask for the bill",
        filler: "Hmm, deixa eu ver…",
        beats: [
            beat("greet and choose a drink", "Olá! O que você vai querer para beber?", "Água ou suco?"),
            beat("order food; offer a dish", "Hoje a gente tem feijoada e frango grelhado. O que você quer comer?", "Feijoada ou frango?"),
            beat("ask how the food tastes", "E aí, o que você está achando da comida?", "Está gostoso ou mais ou menos?"),
            beat("ask for the bill and finish", "Você quer mais alguma coisa ou já trago a conta?", "Mais alguma coisa ou a conta?"),
        ],
        target_structures: [
            ["quero + noun", "tem…?"],
            ["eu queria / gostaria de", "pode me trazer…?"],
            ["conditional politeness", "complaining politely"],
        ],
    },
    Scene {
        id: "meeting_someone",
        tutor_role: "new acquaintance",
        learner_role: "new acquaintance",
        goal: "introduce yourself and find a shared interest",
        filler: "Um momento…",
        beats: [
            beat("exchange names", "Olá! Como você se chama?", "Você se chama Ana ou tem outro nome?"),
            beat("say where you live", "E você mora aqui na cidade ou está só de passagem?", "Mora aqui ou em outra cidade?"),
            beat("find a shared interest", "O que você gosta de fazer no tempo livre?", "Música ou esporte?"),
            beat("suggest another conversation", "Foi ótimo conversar! A gente podia tomar um café um dia desses, que tal?", "Café ou almoço?"),
        ],
        target_structures: [
            ["me chamo", "eu gosto de + noun"],
            ["costumo + infinitive", "moro aqui há + time"],
            ["shared interests", "polite invitations"],
        ],
    },
    Scene {
        id: "school_day",
        tutor_role: "classmate",
        learner_role: "student",
        goal: "talk about subjects, a class project and after-school activities",
        filler: "Deixa eu pensar…",
        beats: [
            beat("name a favorite subject", "Oi! Qual é a sua matéria favorita?", "Matemática ou história?"),
            beat("describe a class", "Me conta: como é essa aula?", "Fácil ou difícil?"),
            beat("describe a project or activity", "Você está fazendo algum projeto na escola?", "Um projeto de ciências ou de arte?"),
            beat("arrange an after-school activity", "Depois da aula, quer fazer alguma coisa junto?", "Jogar bola ou estudar na biblioteca?"),
        ],
        target_structures: [
            ["gosto de + noun", "a aula é + adjective"],
            ["a gente está fazendo", "acho que + clause"],
            ["explain an opinion", "compare learning experiences"],
        ],
    },
    Scene {
        id: "weekend_plans",
        tutor_role: "friend",
        learner_role: "friend",
        goal: "agree an activity, place and time",
        filler: "Hmm, deixa eu ver…",
        beats: [
            beat("choose an activity", "E aí, o que a gente faz no fim de semana?", "Cinema ou praia?"),
            beat("choose a place", "Boa! E onde a gente se encontra?", "No shopping ou na praça?"),
            beat("agree a time", "Que horas fica bom para você?", "De manhã ou de tarde?"),
            beat("confirm the plan", "Então fechou? Te espero lá?", "Fechado ou quer mudar?"),
        ],
        target_structures: [
            ["vamos + infinitive", "quero ir ao / à + place"],
            ["que tal + infinitive?", "a gente podia + infinitive"],
            ["negotiate alternatives", "hypothetical plans"],
        ],
    },
    Scene {
        id: "shopping",
        tutor_role: "shop assistant",
        learner_role: "customer",
        goal: "choose an item, compare options and buy it",
        filler: "Um momento…",
        beats: [
            beat("identify an item", "Olá! Posso ajudar? O que você está procurando?", "Uma camiseta ou um tênis?"),
            beat("choose size and color", "Que tamanho você veste? E qual cor você prefere?", "Azul ou preto?"),
            beat("compare an alternative", "Tem esse outro modelo também. Você prefere este ou aquele?", "Este ou aquele?"),
            beat("ask price and decide", "Gostou? Quer saber quanto custa?", "Vai levar ou vai pensar mais?"),
        ],
        target_structures: [
            ["quero + noun", "quanto custa?"],
            ["prefiro este / aquele", "tem em outra cor?"],
            ["compare value", "negotiate politely"],
        ],
    },
    Scene {
        id: "asking_directions",
        tutor_role: "helpful pedestrian",
        learner_role: "visitor",
        goal: "find a destination and check the route",
        filler: "Deixa eu pensar…",
        beats: [
            beat("ask for a destination", "Olá! Posso ajudar? Para onde você quer ir?", "Para o metrô ou para o museu?"),
            beat("establish a landmark", "Você conhece a praça principal, ali perto da igreja?", "A praça ou a igreja?"),
            beat("explain and confirm a route", "É só seguir reto e depois virar à esquerda na praça. Deu para entender?", "Entendi ou pode repetir?"),
            beat("check understanding and finish", "Tudo certo? Você vai a pé ou pega o ônibus?", "A pé ou de ônibus?"),
        ],
        target_structures: [
            ["onde fica…?", "fica perto / longe"],
            ["pode me dizer como chego a…?", "é só + infinitive"],
            ["clarify ambiguous directions", "compare routes"],
        ],
    },
    Scene {
        id: "hotel_checkin",
        tutor_role: "hotel receptionist",
        learner_role: "guest",
        goal: "check in, ask about facilities and agree checkout",
        filler: "Um momento…",
        beats: [
            beat("greet and confirm reservation", "Boa tarde! A reserva está em qual nome, por favor?", "Silva ou outro nome?"),
            beat("choose a room", "Prefere um quarto com vista ou um mais silencioso?", "Com vista ou mais silencioso?"),
            beat("ask about facilities", "Posso ajudar com mais alguma informação? Quer saber do café da manhã ou da piscina?", "Café da manhã ou piscina?"),
            beat("agree checkout and finish", "Perfeito. E a que horas prefere fazer o check-out?", "De manhã cedo ou ao meio-dia?"),
        ],
        target_structures: [
            ["tenho uma reserva", "tem Wi-Fi / café da manhã?"],
            ["eu gostaria de um quarto + adjective", "o senhor / a senhora poderia + infinitive?"],
            ["request an accommodation", "resolve a reservation problem"],
        ],
    },
    Scene {
        id: "planning_party",
        tutor_role: "friend helping organize",
        learner_role: "party organizer",
        goal: "plan guests, food, activities and timing",
        filler: "Hmm, deixa eu ver…",
        beats: [
            beat("decide who is invited", "E aí, quem a gente vai convidar para a festa?", "Só os amigos ou a família também?"),
            beat("choose food", "E de comida, o que você quer servir?", "Pizza ou churrasco?"),
            beat("choose an activity", "Vai ter alguma atividade na festa?", "Música ou jogos?"),
            beat("confirm when and finish", "Aí a gente fecha tudo. E quando vai ser a festa?", "Sábado ou domingo?"),
        ],
        target_structures: [
            ["vou convidar + noun", "quero + noun"],
            ["a gente podia + infinitive", "vai ter + noun"],
            ["coordinate preferences", "negotiate constraints"],
        ],
    },
];

pub static MANDARIN_SCENES: [Scene; 8] = [
    Scene {
        id: "ordering_food",
        tutor_role: "waiter",
        learner_role: "customer",
        goal: "order food and a drink, then ask for the bill",
        filler: "嗯，让我想想……",
        beats: [
            beat("greet and choose a drink", "您好！请问您想喝点什么？", "茶还是果汁？"),
            beat("order food; offer a dish", "我们有饺子和炒饭，您想吃什么？", "饺子还是炒饭？"),
            beat("ask how the food tastes", "菜怎么样？好吃吗？", "好吃还是一般？"),
            beat("ask for the bill and finish", "您还要别的吗？还是现在买单？", "还要别的还是买单？"),
        ],
        target_structures: [
            ["我要+名词", "有没有……？"],
            ["我想点……", "麻烦给我……"],
            ["conditional politeness", "complaining politely"],
        ],
    },
    Scene {
        id: "meeting_someone",
        tutor_role: "new acquaintance",
        learner_role: "new acquaintance",
        goal: "introduce yourself and find a shared interest",
        filler: "稍等一下……",
        beats: [
            beat("exchange names", "你好！你叫什么名字？", "你叫李华还是别的名字？"),
            beat("say where you live", "你住在哪儿？", "北京还是上海？"),
            beat("find a shared interest", "你平时喜欢做什么？", "看电影还是打球？"),
            beat("suggest another conversation", "下次一起喝杯咖啡，怎么样？", "这周末还是下周？"),
        ],
        target_structures: [
            ["我叫……", "我喜欢……"],
            ["我经常+动词", "我在这儿住了……年了"],
            ["shared interests", "polite invitations"],
        ],
    },
    Scene {
        id: "school_day",
        tutor_role: "classmate",
        learner_role: "student",
        goal: "talk about subjects, a class project and after-school activities",
        filler: "我看看……",
        beats: [
            beat("name a favorite subject", "你最喜欢哪门课？", "数学还是英语？"),
            beat("describe a class", "今天的课怎么样？难不难？", "难还是简单？"),
            beat("describe a project or activity", "你们小组的作业打算做什么？", "做海报还是拍视频？"),
            beat("arrange an after-school activity", "放学以后一起去打球吧？", "打篮球还是踢足球？"),
        ],
        target_structures: [
            ["我喜欢+科目", "……很难/很容易"],
            ["我觉得……", "……比……难"],
            ["explain an opinion", "compare learning experiences"],
        ],
    },
    Scene {
        id: "weekend_plans",
        tutor_role: "friend",
        learner_role: "friend",
        goal: "agree an activity, place and time",
        filler: "嗯，让我想想……",
        beats: [
            beat("choose an activity", "周末你想干什么？", "看电影还是爬山？"),
            beat("choose a place", "我们去哪儿？", "去商场还是去公园？"),
            beat("agree a time", "几点见面？", "上午还是下午？"),
            beat("confirm the plan", "到时候微信联系，那就这么说定了？", "说定了还是再改改？"),
        ],
        target_structures: [
            ["我想+动词", "……点见"],
            ["我们……吧", "要不……？"],
            ["negotiate alternatives", "hypothetical plans"],
        ],
    },
    Scene {
        id: "shopping",
        tutor_role: "shop assistant",
        learner_role: "customer",
        goal: "choose an item, compare options and buy it",
        filler: "稍等一下……",
        beats: [
            beat("identify an item", "您好！您想买点什么？", "衣服还是鞋子？"),
            beat("choose size and color", "您要什么颜色？穿多大的？", "黑色还是白色？"),
            beat("compare an alternative", "这件也不错，您觉得哪件好？", "这件还是那件？"),
            beat("ask price and decide", "这件现在打折，您要不要？", "要还是再看看？"),
        ],
        target_structures: [
            ["多少钱？", "我要这件"],
            ["有没有……一点的？", "……比……便宜"],
            ["compare value", "negotiate politely"],
        ],
    },
    Scene {
        id: "asking_directions",
        tutor_role: "helpful pedestrian",
        learner_role: "visitor",
        goal: "find a destination and check the route",
        filler: "我看看……",
        beats: [
            beat("ask for a destination", "您好，您要去哪儿？", "地铁站还是火车站？"),
            beat("establish a landmark", "您看到前面的红绿灯了吗？", "看到了还是没看到？"),
            beat("explain and confirm a route", "一直往前走，到红绿灯左拐就到了。明白吗？", "左拐还是右拐？"),
            beat("check understanding and finish", "要不要我再说一遍？", "再说一遍还是明白了？"),
        ],
        target_structures: [
            ["……在哪儿？", "往左拐/往右拐"],
            ["请问，……怎么走？", "离这儿远不远？"],
            ["clarify ambiguous directions", "compare routes"],
        ],
    },
    Scene {
        id: "hotel_checkin",
        tutor_role: "hotel receptionist",
        learner_role: "guest",
        goal: "check in, ask about facilities and agree checkout",
        filler: "稍等一下……",
        beats: [
            beat("greet and confirm reservation", "您好，欢迎光临！请问您有预订吗？", "有预订还是没有？"),
            beat("choose a room", "您想要什么样的房间？", "大床房还是双床房？"),
            beat("ask about facilities", "酒店有早餐和游泳池，您想问什么？", "早餐还是游泳池？"),
            beat("agree checkout and finish", "您打算什么时候退房？", "明天还是后天？"),
        ],
        target_structures: [
            ["我叫……", "有没有……？"],
            ["我订了……", "可以……吗？"],
            ["request an accommodation", "resolve a reservation problem"],
        ],
    },
    Scene {
        id: "planning_party",
        tutor_role: "friend helping organize",
        learner_role: "party organizer",
        goal: "plan guests, food, activities and timing",
        filler: "嗯，让我想想……",
        beats: [
            beat("decide who is invited", "你想请谁来？", "同学还是同事？"),
            beat("choose food", "我们准备什么吃的？", "披萨还是饺子？"),
            beat("choose an activity", "派对上玩什么？", "唱歌还是玩游戏？"),
            beat("confirm when and finish", "那派对定在什么时候？", "周五晚上还是周六？"),
        ],
        target_structures: [
            ["我想请……", "我们吃……"],
            ["把……准备好", "先……，然后……"],
            ["coordinate preferences", "negotiate constraints"],
        ],
    },
];

pub static HINDI_SCENES: [Scene; 8] = [
    Scene {
        id: "ordering_food",
        tutor_role: "waiter",
        learner_role: "customer",
        goal: "order food and a drink, then ask for the bill",
        filler: "Hmm, ek minute…",
        beats: [
            beat("greet and choose a drink", "Namaste! Aap kya peena chahenge?", "Paani ya chai?"),
            beat("order food; offer a dish", "Aaj hamare paas dal, paneer aur biryani hai. Aap kya khaana chahenge?", "Paneer ya biryani?"),
            beat("ask how the food tastes", "Khaana kaisa laga aapko?", "Bahut achha ya bas theek-theek?"),
            beat("ask for the bill and finish", "Kuch aur chahiye, ya bill le aaun?", "Kuch aur ya bill?"),
        ],
        target_structures: [
            ["mujhe … chahiye", "kya aapke paas … hai?"],
            ["main … lena chahunga / chahungi", "kya aap … la sakte hain?"],
            ["conditional politeness", "complaining politely"],
        ],
    },
    Scene {
        id: "meeting_someone",
        tutor_role: "new acquaintance",
        learner_role: "new acquaintance",
        goal: "introduce yourself and find a shared interest",
        filler: "Ek minute…",
        beats: [
            beat("exchange names", "Hello! Tumhara naam kya hai?", "Tumhara naam Priya hai ya kuch aur?"),
            beat("say where you live", "Aur tum kahan se ho?", "Dilli se ya kahin aur se?"),
            beat("find a shared interest", "Tumhe khaali waqt mein kya karna pasand hai?", "Cricket ya gaane?"),
            beat("suggest another conversation", "Phir kabhi milke baat karein?", "Kal ya weekend pe?"),
        ],
        target_structures: [
            ["mera naam … hai", "mujhe … pasand hai"],
            ["main … se hoon", "mujhe … mein dilchaspi hai"],
            ["shared interests", "polite invitations"],
        ],
    },
    Scene {
        id: "school_day",
        tutor_role: "classmate",
        learner_role: "student",
        goal: "talk about subjects, a class project and after-school activities",
        filler: "Sochne do…",
        beats: [
            beat("name a favorite subject", "Tumhara favourite subject kaun sa hai?", "Maths ya Hindi?"),
            beat("describe a class", "Aaj ki class kaisi thi?", "Mazedaar ya boring?"),
            beat("describe a project or activity", "Class mein abhi tum log kya kar rahe ho?", "Koi project ya presentation?"),
            beat("arrange an after-school activity", "School ke baad kuch saath karein?", "Padhai ya cricket?"),
        ],
        target_structures: [
            ["mujhe … pasand hai", "… kaisa hai / kaisi hai?"],
            ["mujhe lagta hai ki …", "hum … kar rahe hain"],
            ["explain an opinion", "compare learning experiences"],
        ],
    },
    Scene {
        id: "weekend_plans",
        tutor_role: "friend",
        learner_role: "friend",
        goal: "agree an activity, place and time",
        filler: "Hmm, ek minute…",
        beats: [
            beat("choose an activity", "Weekend pe kya karein?", "Film ya ghoomna?"),
            beat("choose a place", "Aur kahan milein?", "Mere ghar pe ya bazaar mein?"),
            beat("agree a time", "Tumhe kitne baje theek rahega?", "Teen baje ya paanch baje?"),
            beat("confirm the plan", "Toh pakka, Shanivaar ko bazaar mein milte hain?", "Pakka, ya thoda der se?"),
        ],
        target_structures: [
            ["chalo … karein?", "Shanivaar ko / teen baje"],
            ["main … karna chahunga / chahungi", "kya tumhe … achha lagega?"],
            ["negotiate alternatives", "hypothetical plans"],
        ],
    },
    Scene {
        id: "shopping",
        tutor_role: "shop assistant",
        learner_role: "customer",
        goal: "choose an item, compare options and buy it",
        filler: "Ek minute…",
        beats: [
            beat("identify an item", "Namaste! Boliye, aapko kya chahiye?", "Kurta ya T-shirt?"),
            beat("choose size and color", "Aapko kaun sa size aur kaun sa rang chahiye?", "Neela medium ya kaala large?"),
            beat("compare an alternative", "Yeh ek aur design hai. Aapko kaun sa zyada pasand aaya?", "Pehla ya doosra?"),
            beat("ask price and decide", "Yeh hamara sabse popular design hai. Aap kuch aur poochna chahenge?", "Daam ke baare mein ya size ke baare mein?"),
        ],
        target_structures: [
            ["mujhe … chahiye", "yeh kitne ka hai?"],
            ["mujhe … size mein chahiye", "yeh mujhe … se zyada pasand hai"],
            ["compare value", "negotiate politely"],
        ],
    },
    Scene {
        id: "asking_directions",
        tutor_role: "helpful pedestrian",
        learner_role: "visitor",
        goal: "find a destination and check the route",
        filler: "Hmm, ek minute…",
        beats: [
            beat("ask for a destination", "Namaste, koi madad chahiye? Aapko kahan jaana hai?", "Station ya museum?"),
            beat("establish a landmark", "Aap yahan kuch pehchaante hain, jaise mandir ya bazaar?", "Mandir ya bazaar?"),
            beat("explain and confirm a route", "Seedha mandir tak jaaiye, phir baayen mud jaaiye. Aap paidal jaayenge ya bus se?", "Paidal ya bus se?"),
            beat("check understanding and finish", "Toh ab aap kaise jaayenge?", "Pehle seedha ya pehle baayen?"),
        ],
        target_structures: [
            ["… kahan hai?", "main … kaise jaaun?"],
            ["kya aap bata sakte hain ki … kahan hai?", "mujhe … mudna hoga"],
            ["clarify ambiguous directions", "compare routes"],
        ],
    },
    Scene {
        id: "hotel_checkin",
        tutor_role: "hotel receptionist",
        learner_role: "guest",
        goal: "check in, ask about facilities and agree checkout",
        filler: "Ek minute…",
        beats: [
            beat("greet and confirm reservation", "Namaste! Kya aapki booking hai?", "Booking hai ya nahi?"),
            beat("choose a room", "Aapko kaisa kamra chahiye?", "Single ya double?"),
            beat("ask about facilities", "Hotel ke baare mein kuch aur poochna hai?", "Naashta ya wifi?"),
            beat("agree checkout and finish", "Aur aap kab tak rukenge?", "Ravivaar tak ya Somvaar tak?"),
        ],
        target_structures: [
            ["meri booking … ke naam se hai", "kya yahan … hai?"],
            ["mujhe … waala kamra chahiye", "checkout kab tak karna hoga?"],
            ["request an accommodation", "resolve a reservation problem"],
        ],
    },
    Scene {
        id: "planning_party",
        tutor_role: "friend helping organize",
        learner_role: "party organizer",
        goal: "plan guests, food, activities and timing",
        filler: "Sochne do…",
        beats: [
            beat("decide who is invited", "Tumhare hisaab se kis kis ko bulayein?", "Sirf dost ya parivaar bhi?"),
            beat("choose food", "Aur khaane mein kya rakhein?", "Pizza ya samose?"),
            beat("choose an activity", "Party mein kya karenge?", "Gaane ya khel?"),
            beat("confirm when and finish", "Party kab rakhein?", "Shukravaar ya Shanivaar?"),
        ],
        target_structures: [
            ["hum … ko bulayenge", "khaane mein … hoga"],
            ["hum … kar sakte hain", "chalo … karte hain"],
            ["coordinate preferences", "negotiate constraints"],
        ],
    },
];

/// Scenes for a language id. Spanish (`"es"`) is served by
/// `crate::spanish::scenes` and returns `None` here.
pub fn scenes_for(language_id: &str) -> Option<&'static [Scene; 8]> {
    match language_id {
        "nb" => Some(&NORWEGIAN_SCENES),
        "en" => Some(&ENGLISH_SCENES),
        "fr" => Some(&FRENCH_SCENES),
        "de" => Some(&GERMAN_SCENES),
        "it" => Some(&ITALIAN_SCENES),
        "pt" => Some(&PORTUGUESE_SCENES),
        "zh" => Some(&MANDARIN_SCENES),
        "hi" => Some(&HINDI_SCENES),
        _ => None,
    }
}

/// Language ids this module carries scenes for.
pub static SCENE_LANGUAGES: [&str; 8] = ["nb", "en", "fr", "de", "it", "pt", "zh", "hi"];


#[cfg(test)]
mod tests {
    use super::*;

    fn all_sets() -> Vec<(&'static str, &'static [Scene; 8])> {
        SCENE_LANGUAGES
            .iter()
            .map(|id| (*id, scenes_for(id).expect("registered language has scenes")))
            .collect()
    }

    #[test]
    fn every_language_has_eight_scenes_in_the_shared_order() {
        for (lang, scenes) in all_sets() {
            assert_eq!(scenes.len(), 8, "{lang}");
            for (scene, want) in scenes.iter().zip(SCENE_IDS.iter()) {
                assert_eq!(&scene.id, want, "{lang} scene order");
            }
        }
    }

    #[test]
    fn beats_are_complete_and_paced() {
        for (lang, scenes) in all_sets() {
            for scene in scenes.iter() {
                assert_eq!(scene.beats.len(), 4, "{lang}/{}", scene.id);
                for beat in scene.beats.iter() {
                    assert!(beat.max_turns > 0, "{lang}/{}", scene.id);
                    assert!(!beat.goal.is_empty(), "{lang}/{}", scene.id);
                    assert!(!beat.opener.trim().is_empty(), "{lang}/{}", scene.id);
                    assert!(!beat.options.trim().is_empty(), "{lang}/{}", scene.id);
                }
            }
        }
    }

    /// Mirrors the invariant `spanish::scenes` asserts. Mandarin writes the
    /// full-width form, so both are accepted.
    #[test]
    fn openers_and_options_are_questions() {
        for (lang, scenes) in all_sets() {
            for scene in scenes.iter() {
                for beat in scene.beats.iter() {
                    for (field, text) in [("opener", beat.opener), ("options", beat.options)] {
                        assert!(
                            text.ends_with('?') || text.ends_with('？'),
                            "{lang}/{}/{field} must end with a question mark: {text}",
                            scene.id
                        );
                    }
                }
            }
        }
    }

    #[test]
    fn target_structures_cover_every_dial_position() {
        for (lang, scenes) in all_sets() {
            for scene in scenes.iter() {
                for dial in 0u8..=2 {
                    let row = scene.targets(dial);
                    for cell in row.iter() {
                        assert!(!cell.trim().is_empty(), "{lang}/{} dial {dial}", scene.id);
                    }
                }
                // Out-of-range dials clamp rather than panicking.
                assert_eq!(scene.targets(9), scene.targets(2), "{lang}/{}", scene.id);
            }
        }
    }

    /// The English metadata keys the tutor's deterministic progression, so it
    /// must be identical in every language. A translated `goal` would silently
    /// desynchronise that language from the engine.
    #[test]
    fn english_metadata_is_identical_across_languages() {
        let reference = scenes_for(SCENE_LANGUAGES[0]).unwrap();
        for (lang, scenes) in all_sets() {
            for (scene, base) in scenes.iter().zip(reference.iter()) {
                assert_eq!(scene.id, base.id, "{lang}");
                assert_eq!(scene.tutor_role, base.tutor_role, "{lang}/{}", scene.id);
                assert_eq!(scene.learner_role, base.learner_role, "{lang}/{}", scene.id);
                assert_eq!(scene.goal, base.goal, "{lang}/{}", scene.id);
                for (beat, bbase) in scene.beats.iter().zip(base.beats.iter()) {
                    assert_eq!(beat.goal, bbase.goal, "{lang}/{}", scene.id);
                }
                // The advanced row is a shared English label set.
                assert_eq!(
                    scene.target_structures[2], base.target_structures[2],
                    "{lang}/{}", scene.id
                );
            }
        }
    }

    /// Dialogue must actually differ per language; identical openers would mean
    /// a language was left untranslated.
    #[test]
    fn dialogue_is_distinct_per_language() {
        let sets = all_sets();
        for (i, (lang_a, a)) in sets.iter().enumerate() {
            for (lang_b, b) in sets.iter().skip(i + 1) {
                let shared = a
                    .iter()
                    .zip(b.iter())
                    .filter(|(x, y)| x.beats[0].opener == y.beats[0].opener)
                    .count();
                assert_eq!(shared, 0, "{lang_a} and {lang_b} share opening lines");
            }
        }
    }

    #[test]
    fn fillers_are_present_and_reused_not_unique_per_scene() {
        for (lang, scenes) in all_sets() {
            let mut distinct = std::collections::HashSet::new();
            for scene in scenes.iter() {
                assert!(!scene.filler.trim().is_empty(), "{lang}/{}", scene.id);
                distinct.insert(scene.filler);
            }
            assert!(distinct.len() <= 5, "{lang} has {} fillers", distinct.len());
        }
    }

    #[test]
    fn spanish_is_not_served_here() {
        // Spanish keeps its own untouched set in crate::spanish::scenes.
        assert!(scenes_for("es").is_none());
        assert!(scenes_for("xx").is_none());
        assert!(!SCENE_LANGUAGES.contains(&"es"));
    }

    #[test]
    fn mandarin_content_carries_no_pinyin() {
        let zh = scenes_for("zh").unwrap();
        for scene in zh.iter() {
            for beat in scene.beats.iter() {
                for text in [beat.opener, beat.options] {
                    let latin: String = text.chars().filter(|c| c.is_ascii_alphabetic()).collect();
                    assert!(
                        latin.is_empty(),
                        "Mandarin {} contains Latin letters: {text}",
                        scene.id
                    );
                }
            }
        }
    }

    #[test]
    fn beat_lookup_clamps_past_the_last_beat() {
        let scenes = scenes_for("de").unwrap();
        let scene = &scenes[0];
        assert_eq!(scene.beat(0).goal, scene.beats[0].goal);
        assert_eq!(scene.beat(99).goal, scene.beats[3].goal);
    }

    /// Hindi is taught in Roman script by design (docs/SCENE-AUTHORING.md):
    /// learners speak it and never read Devanagari, so no learner-facing
    /// string may contain a Devanagari codepoint (U+0900..=U+097F) or an IAST
    /// diacritic. Plain ASCII letters only.
    #[test]
    fn hindi_content_is_roman_script_only() {
        let hi = scenes_for("hi").unwrap();
        for scene in hi.iter() {
            let mut texts = vec![scene.filler];
            for beat in scene.beats.iter() {
                texts.push(beat.opener);
                texts.push(beat.options);
            }
            for row in &scene.target_structures[..2] {
                texts.extend(row.iter().copied());
            }
            for text in texts {
                assert!(
                    !text.chars().any(|c| ('\u{0900}'..='\u{097F}').contains(&c)),
                    "Hindi {} contains Devanagari: {text}",
                    scene.id
                );
                assert!(
                    text.chars().filter(|c| c.is_alphabetic()).all(|c| c.is_ascii()),
                    "Hindi {} contains a non-ASCII letter (IAST diacritic?): {text}",
                    scene.id
                );
            }
        }
    }

    /// Service scenes address the learner as aap, peer scenes as tum, and no
    /// scene mixes the two. tu is never modelled.
    #[test]
    fn hindi_register_is_split_by_scene_and_never_mixed() {
        let hi = scenes_for("hi").unwrap();
        let service = ["ordering_food", "shopping", "hotel_checkin", "asking_directions"];
        let aap = ["aap", "aapko", "aapka", "aapki", "aapke", "aapne"];
        let tum = ["tum", "tumhe", "tumhara", "tumhari", "tumhare", "tumne"];
        let words = |text: &str| -> Vec<String> {
            text.split(|c: char| !c.is_alphanumeric())
                .filter(|w| !w.is_empty())
                .map(|w| w.to_lowercase())
                .collect()
        };
        for scene in hi.iter() {
            let mut has_aap = false;
            let mut has_tum = false;
            for beat in scene.beats.iter() {
                for text in [beat.opener, beat.options] {
                    for w in words(text) {
                        assert_ne!(w, "tu", "Hindi {} models tu: {text}", scene.id);
                        has_aap |= aap.contains(&w.as_str());
                        has_tum |= tum.contains(&w.as_str());
                    }
                }
            }
            assert!(!(has_aap && has_tum), "Hindi {} mixes aap and tum", scene.id);
            if service.contains(&scene.id) {
                assert!(has_aap && !has_tum, "Hindi service scene {} should use aap", scene.id);
            } else {
                assert!(has_tum && !has_aap, "Hindi peer scene {} should use tum", scene.id);
            }
        }
    }
}
