'use client';

import { invoke } from '@tauri-apps/api/core';
import { appDataDir } from '@tauri-apps/api/path';
import { listen } from '@tauri-apps/api/event';
import { useCallback, useEffect, useState } from 'react';
import { AlertCircle, Mic, X } from 'lucide-react';
import type { SummaryResponse } from '@/types/summary';
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert';
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from '@/components/ui/tooltip';
import RecorderBar from '@/components/Meeting/RecorderBar';
import Analytics from '@/lib/analytics';
import { useRecordingState } from '@/contexts/RecordingStateContext';
import { useTranscriptSession } from '@/contexts/TranscriptContext';
import { openManualNotesWindow } from '@/services/manualNotesService';

interface RecordingControlsProps {
  isRecording: boolean;
  /**
   * Kept for API compatibility with older callers. The redesigned recorder never
   * renders these values because they were generated by the UI rather than by the
   * capture pipeline.
   */
  barHeights: string[];
  onRecordingStop: (callApi?: boolean) => void;
  onRecordingStart: () => void | Promise<void>;
  onTranscriptReceived: (summary: SummaryResponse) => void;
  onTranscriptionError?: (message: string) => void;
  onStopInitiated?: () => void;
  isRecordingDisabled: boolean;
  isParentProcessing: boolean;
  selectedDevices?: {
    micDevice: string | null;
    systemDevice: string | null;
  };
  meetingName?: string;
}

export const RecordingControls: React.FC<RecordingControlsProps> = ({
  isRecording,
  barHeights: _barHeights,
  onRecordingStop,
  onRecordingStart,
  onTranscriptReceived: _onTranscriptReceived,
  onTranscriptionError,
  onStopInitiated,
  isRecordingDisabled,
  isParentProcessing,
  selectedDevices,
  meetingName,
}) => {
  // RecordingStateContext stays authoritative so tray actions and in-app controls
  // remain synchronized.
  const recordingState = useRecordingState();
  const isPaused = recordingState.isPaused;
  const { currentMeetingId, captionsVisible, setCaptionsVisible } = useTranscriptSession();

  const [isProcessing, setIsProcessing] = useState(false);
  const [isStarting, setIsStarting] = useState(false);
  const [isStopping, setIsStopping] = useState(false);
  const [isPausing, setIsPausing] = useState(false);
  const [isResuming, setIsResuming] = useState(false);
  const [isValidatingModel] = useState(false);
  const [speechDetected, setSpeechDetected] = useState(false);
  const [deviceError, setDeviceError] = useState<{ title: string; message: string } | null>(null);

  useEffect(() => {
    const checkTauri = async () => {
      try {
        const result = await invoke('is_recording');
        console.log('Tauri is initialized and ready, is_recording result:', result);
      } catch (error) {
        console.error('Tauri initialization error:', error);
      }
    };
    void checkTauri();
  }, []);

  const handleStartRecording = useCallback(async () => {
    if (isStarting || isValidatingModel) return;

    console.log('Starting recording...');
    console.log('Selected devices:', selectedDevices);
    console.log('Meeting name:', meetingName);
    console.log('Current isRecording state:', isRecording);

    setSpeechDetected(false);
    setDeviceError(null);
    setIsStarting(true);

    try {
      // Keep validation and native start in the existing parent callback. The visual
      // redesign must not create a second recorder state machine.
      await onRecordingStart();
    } catch (error) {
      console.error('Failed to start recording:', error);
      const errorMsg = error instanceof Error ? error.message : String(error);

      if (errorMsg.includes('microphone') || errorMsg.includes('mic') || errorMsg.includes('input')) {
        setDeviceError({
          title: 'Microphone Not Available',
          message: 'Unable to access your microphone. Please check that:\n• Your microphone is connected\n• The app has microphone permissions\n• No other app is using the microphone',
        });
      } else if (errorMsg.includes('system audio') || errorMsg.includes('speaker') || errorMsg.includes('output')) {
        setDeviceError({
          title: 'System Audio Not Available',
          message: 'Unable to capture system audio. Please check your system-audio device and macOS permissions.',
        });
      } else if (errorMsg.includes('permission')) {
        setDeviceError({
          title: 'Permission Required',
          message: 'Recording permissions are required. Grant microphone and system-audio permissions in System Settings, then try again.',
        });
      } else {
        setDeviceError({
          title: 'Recording Failed',
          message: 'Unable to start recording. Please check your audio device settings and try again.',
        });
      }
    } finally {
      setIsStarting(false);
    }
  }, [isRecording, isStarting, isValidatingModel, meetingName, onRecordingStart, selectedDevices]);

  const stopRecordingAction = useCallback(async () => {
    console.log('Executing stop recording...');
    try {
      setIsProcessing(true);
      const dataDir = await appDataDir();
      const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
      const savePath = `${dataDir}/recording-${timestamp}.wav`;
      console.log('Saving recording to:', savePath);
      console.log('About to call stop_recording command');

      const result = await invoke('stop_recording', {
        args: {
          save_path: savePath,
        },
      });
      console.log('stop_recording command completed successfully:', result);

      setIsProcessing(false);
      Analytics.trackTranscriptionSuccess();
      onRecordingStop(true);
    } catch (error) {
      console.error('Failed to stop recording:', error);
      if (error instanceof Error) {
        console.error('Error details:', {
          message: error.message,
          name: error.name,
          stack: error.stack,
        });
        if (error.message.includes('No recording in progress')) return;
      } else if (typeof error === 'string' && error.includes('No recording in progress')) {
        return;
      } else if (error && typeof error === 'object' && 'toString' in error) {
        if (error.toString().includes('No recording in progress')) return;
      }

      setIsProcessing(false);
      onRecordingStop(false);
    } finally {
      setIsStopping(false);
    }
  }, [onRecordingStop]);

  const handleStopRecording = useCallback(async () => {
    console.log(
      'handleStopRecording called - isRecording:',
      isRecording,
      'isStarting:',
      isStarting,
      'isStopping:',
      isStopping,
    );
    if (!isRecording || isStarting || isStopping) return;

    onStopInitiated?.();
    setIsStopping(true);
    await stopRecordingAction();
  }, [isRecording, isStarting, isStopping, onStopInitiated, stopRecordingAction]);

  const handlePauseRecording = useCallback(async () => {
    if (!isRecording || isPaused || isPausing) return;
    setIsPausing(true);
    try {
      await invoke('pause_recording');
      console.log('Recording paused successfully');
    } catch (error) {
      console.error('Failed to pause recording:', error);
    } finally {
      setIsPausing(false);
    }
  }, [isPaused, isPausing, isRecording]);

  const handleResumeRecording = useCallback(async () => {
    if (!isRecording || !isPaused || isResuming) return;
    setIsResuming(true);
    try {
      await invoke('resume_recording');
      console.log('Recording resumed successfully');
    } catch (error) {
      console.error('Failed to resume recording:', error);
    } finally {
      setIsResuming(false);
    }
  }, [isPaused, isRecording, isResuming]);

  useEffect(() => {
    console.log('Setting up recording event listeners');
    let unsubscribes: Array<() => void> = [];

    const setupListeners = async () => {
      try {
        const transcriptErrorUnsubscribe = await listen('transcript-error', (event) => {
          console.error('Transcription error received:', event.payload);
          const errorMessage = event.payload as string;
          Analytics.trackTranscriptionError(errorMessage);
          setIsProcessing(false);
          onRecordingStop(false);
          onTranscriptionError?.(errorMessage);
        });

        const transcriptionErrorUnsubscribe = await listen('transcription-error', (event) => {
          console.error('Transcription error received:', event.payload);
          let errorMessage: string;
          if (typeof event.payload === 'object' && event.payload !== null) {
            const payload = event.payload as {
              error: string;
              userMessage: string;
              actionable: boolean;
            };
            errorMessage = payload.userMessage || payload.error;
          } else {
            errorMessage = String(event.payload);
          }

          Analytics.trackTranscriptionError(errorMessage);
          setIsProcessing(false);
          onRecordingStop(false);
          // Structured transcription errors are already surfaced by the global
          // modal/toast listener, preserving the legacy single-notification behavior.
        });

        const speechDetectedUnsubscribe = await listen('speech-detected', () => {
          setSpeechDetected(true);
        });

        unsubscribes = [
          transcriptErrorUnsubscribe,
          transcriptionErrorUnsubscribe,
          speechDetectedUnsubscribe,
        ];
      } catch (error) {
        console.error('Failed to set up recording event listeners:', error);
      }
    };

    void setupListeners();
    return () => {
      unsubscribes.forEach((unsubscribe) => unsubscribe?.());
    };
  }, [onRecordingStop, onTranscriptionError]);

  const handlePauseResume = () => {
    if (isPaused) {
      Analytics.trackButtonClick('resume_recording', 'recording_controls');
      void handleResumeRecording();
    } else {
      Analytics.trackButtonClick('pause_recording', 'recording_controls');
      void handlePauseRecording();
    }
  };

  return (
    <TooltipProvider>
      <div className="flex flex-col gap-2">
        {isRecording ? (
          <RecorderBar
            isPaused={isPaused}
            isStopping={isStopping}
            isPausing={isPausing}
            isResuming={isResuming}
            isProcessing={isProcessing || isParentProcessing}
            recordingDuration={recordingState.recordingDuration}
            speechDetected={speechDetected}
            // The existing `audio-levels` command is a simulated sine wave. Do not
            // pass it into the production recorder. Keep the meter neutral until the
            // capture pipeline exposes a genuine amplitude contract.
            audioLevel={null}
            captionsVisible={captionsVisible}
            onPauseResume={handlePauseResume}
            onStop={() => {
              Analytics.trackButtonClick('stop_recording', 'recording_controls');
              void handleStopRecording();
            }}
            onToggleCaptions={() => setCaptionsVisible(!captionsVisible)}
            onOpenNotes={() => {
              if (currentMeetingId) void openManualNotesWindow(currentMeetingId).catch(() => {});
            }}
          />
        ) : (
          <Tooltip>
            <TooltipTrigger asChild>
              <button
                type="button"
                onClick={() => {
                  Analytics.trackButtonClick('start_recording', 'recording_controls');
                  void handleStartRecording();
                }}
                disabled={isStarting || isProcessing || isRecordingDisabled || isValidatingModel}
                className="inline-grid h-12 w-12 place-items-center rounded-full bg-record text-white transition-opacity duration-150 hover:opacity-90 disabled:opacity-40"
                aria-label="Start recording"
              >
                <Mic className="h-5 w-5" strokeWidth={1.75} />
              </button>
            </TooltipTrigger>
            <TooltipContent>
              <p>Start recording</p>
            </TooltipContent>
          </Tooltip>
        )}

        {deviceError && (
          <Alert variant="destructive" className="relative border-danger bg-surface text-danger">
            <AlertCircle className="h-5 w-5" />
            <button
              type="button"
              onClick={() => setDeviceError(null)}
              className="absolute right-3 top-3 text-danger transition-opacity hover:opacity-75"
              aria-label="Close alert"
            >
              <X className="h-4 w-4" />
            </button>
            <AlertTitle className="font-semibold">{deviceError.title}</AlertTitle>
            <AlertDescription>
              {deviceError.message.split('\n').map((line, index) => (
                <div key={`${index}-${line}`} className={index > 0 ? 'ml-2' : ''}>
                  {line}
                </div>
              ))}
            </AlertDescription>
          </Alert>
        )}
      </div>
    </TooltipProvider>
  );
};
