'use client';

import { useEffect, useRef, useState, type RefObject } from 'react';
import { Check, ChevronDown, FileCheck2, Languages, Loader2, Sparkles } from 'lucide-react';
import { toast } from 'sonner';
import type { Summary, SummaryResponse, Transcript } from '@/types';
import { BlockNoteSummaryView, type BlockNoteSummaryViewRef } from '@/components/AISummary/BlockNoteSummaryView';
import type { ModelConfig } from '@/components/ModelSettingsModal';
import { SummaryGeneratorButtonGroup } from './SummaryGeneratorButtonGroup';
import { SummaryUpdaterButtonGroup } from './SummaryUpdaterButtonGroup';
import { Button } from '@/components/ui/button';
import { Popover, PopoverTrigger, PopoverContent } from '@/components/ui/popover';
import { LanguagePickerPopover } from '@/components/LanguagePickerPopover';
import { useRecentLanguages } from '@/hooks/useRecentLanguages';
import { useConfig } from '@/contexts/ConfigContext';
import { labelForCode } from '@/lib/summary-languages';
import { parseSummaryData } from '@/lib/summary-input';
import { AUTO_SUMMARY_CHOICE_KEY } from '@/lib/post-meeting-flow';
import type { MeetingExportFormat } from '@/lib/meeting-export';
import ExportSheet from '@/components/Meeting/ExportSheet';
import MeetingOutcomeWorkspace from '@/components/Meeting/MeetingOutcomeWorkspace';
import { readMeetingSummaryLanguage, saveMeetingSummaryLanguage, type SummaryLanguageStorage } from '@/lib/summary-language-preferences';

type Status='idle'|'processing'|'summarizing'|'regenerating'|'completed'|'error';
interface SummaryPanelProps { meeting:{id:string;title:string;created_at:string}; meetingTitle:string; onTitleChange:(title:string)=>void; isEditingTitle:boolean; onStartEditTitle:()=>void; onFinishEditTitle:()=>void; isTitleDirty:boolean; summaryRef:RefObject<BlockNoteSummaryViewRef>; isSaving:boolean; onSaveAll:()=>Promise<void>; onCopySummary:()=>Promise<void>; onOpenFolder:()=>Promise<void>; aiSummary:Summary|null; summaryStatus:Status; transcripts:Transcript[]; modelConfig:ModelConfig; setModelConfig:(config:ModelConfig|((previous:ModelConfig)=>ModelConfig))=>void; onSaveModelConfig:(config?:ModelConfig)=>Promise<void>; onGenerateSummary:(prompt:string)=>Promise<void>; onStopGeneration:()=>void; customPrompt:string; summaryResponse:SummaryResponse|null; onSaveSummary:(summary:Summary|{markdown?:string;summary_json?:any[]})=>Promise<void>; onSummaryChange:(summary:Summary)=>void; onDirtyChange:(dirty:boolean)=>void; summaryError:string|null; onRegenerateSummary:()=>Promise<void>; getSummaryStatusMessage:(status:Status)=>string; availableTemplates:Array<{id:string;name:string;description:string}>; selectedTemplate:string; onTemplateSelect:(id:string,name:string)=>void; isModelConfigLoading?:boolean; onOpenModelSettings?:(open:()=>void)=>void }

export function SummaryPanel(props:SummaryPanelProps){
  const {meeting,aiSummary,summaryStatus,summaryError,transcripts,modelConfig,summaryRef}=props; const {isAutoSummary,toggleIsAutoSummary}=useConfig();
  const [firstChoice,setFirstChoice]=useState(false); const [summaryLang,setSummaryLang]=useState<string|null>(null); const [summaryLangStorage,setSummaryLangStorage]=useState<SummaryLanguageStorage>('metadata'); const [langPickerOpen,setLangPickerOpen]=useState(false); const [exportingFormat,setExportingFormat]=useState<MeetingExportFormat|null>(null); const [exportOpen,setExportOpen]=useState(false); const [exportFormat,setExportFormat]=useState<MeetingExportFormat>('markdown');
  const languageLoadVersion=useRef(0); const activeMeetingId=useRef(meeting.id); activeMeetingId.current=meeting.id; const saveRunning=useRef(false); const pendingLanguage=useRef<{meetingId:string;version:number;language:string|null;rollback:{language:string|null;storage:SummaryLanguageStorage}}|null>(null); const languageVersion=useRef(0); const {addRecent}=useRecentLanguages();
  const busy=['processing','summarizing','regenerating'].includes(summaryStatus); const hasSummary=Boolean(parseSummaryData(aiSummary)); const localProvider=modelConfig.provider==='builtin-ai'||modelConfig.provider==='ollama'; const providerLabel=modelConfig.provider==='openai-codex'?'Connected ChatGPT':modelConfig.provider==='builtin-ai'?'Built-in AI':modelConfig.provider==='ollama'?'Ollama':modelConfig.provider;
  useEffect(()=>{try{setFirstChoice(!localStorage.getItem(AUTO_SUMMARY_CHOICE_KEY))}catch{setFirstChoice(true)}let cancelled=false;const version=++languageLoadVersion.current;void readMeetingSummaryLanguage(meeting.id).then(stored=>{if(!cancelled&&version===languageLoadVersion.current){setSummaryLang(stored.language);setSummaryLangStorage(stored.storage)}}).catch(()=>{if(!cancelled)toast.warning('Could not load saved summary language')});return()=>{cancelled=true}},[meeting.id]);
  const persistLanguage=async()=>{if(saveRunning.current)return;saveRunning.current=true;try{while(pendingLanguage.current){const request=pendingLanguage.current;try{const saved=await saveMeetingSummaryLanguage(request.meetingId,request.language);if(pendingLanguage.current?.version===request.version&&activeMeetingId.current===request.meetingId){setSummaryLang(saved.language);setSummaryLangStorage(saved.storage);if(request.language)addRecent(request.language)}}catch{if(pendingLanguage.current?.version===request.version&&activeMeetingId.current===request.meetingId){setSummaryLang(request.rollback.language);setSummaryLangStorage(request.rollback.storage);toast.error('Failed to save summary language')}}if(pendingLanguage.current?.version===request.version)pendingLanguage.current=null}}finally{saveRunning.current=false}};
  const changeLanguage=(language:string|null)=>{++languageLoadVersion.current;pendingLanguage.current={version:++languageVersion.current,meetingId:meeting.id,language,rollback:{language:summaryLang,storage:summaryLangStorage}};setSummaryLang(language);setLangPickerOpen(false);void persistLanguage()};
  const generate=async(prompt:string)=>{const before=new CustomEvent('meetodds:before-summary-generation',{cancelable:true,detail:{meetingId:meeting.id}});if(!window.dispatchEvent(before)){toast.info('Save or cancel your action edits before regenerating.');return}if(saveRunning.current){toast.info('Wait for your summary language to save, then generate.');return}try{if(hasSummary)await props.onSaveAll();try{localStorage.setItem(AUTO_SUMMARY_CHOICE_KEY,'chosen');setFirstChoice(false)}catch{}await props.onGenerateSummary(prompt)}catch{toast.error('Could not prepare the summary. Save your edits and retry.')}};
  const exportSummary=async(format:MeetingExportFormat)=>{if(exportingFormat)return;setExportingFormat(format);try{await props.onSaveAll();setExportFormat(format);setExportOpen(true)}catch{toast.error('Save your summary edits before exporting')}finally{setExportingFormat(null)}};
  const languageSlot=<Popover open={langPickerOpen} onOpenChange={setLangPickerOpen}><PopoverTrigger asChild><Button type="button" variant="outline" disabled={busy} className="h-11 rounded-[10px] text-[11px]" aria-label="Set summary language"><Languages size={15}/>{summaryLang?labelForCode(summaryLang):'Auto language'}<ChevronDown size={12}/></Button></PopoverTrigger><PopoverContent align="end" className="w-auto border-0 bg-transparent p-0 shadow-none"><LanguagePickerPopover value={summaryLang} onChange={changeLanguage} onClose={()=>setLangPickerOpen(false)} autoSubtitle={summaryLangStorage==='local_fallback'?'Saved on this device':'Uses dominant transcript language'}/></PopoverContent></Popover>;
  const controls=<SummaryGeneratorButtonGroup {...props} onGenerateSummary={generate} hasTranscripts={transcripts.length>0} hasSummary={hasSummary} languageSlot={languageSlot}/>;
  const providerDetail=`${providerLabel}${modelConfig.model?` · ${modelConfig.model}`:''}${localProvider?' · on-device':''}`;
  return <div className="flex min-h-0 min-w-0 flex-1 flex-col bg-bg"><ExportSheet meetingId={meeting.id} open={exportOpen} onOpenChange={setExportOpen} initialFormat={exportFormat}/><div className="min-h-0 flex-1 overflow-y-auto custom-scrollbar"><div className="mx-auto w-full max-w-[760px] space-y-5 px-6 pb-10 pt-2">
    <ol aria-label="Post-meeting progress" className="flex items-center gap-5 font-mono text-[9.5px] text-3"><li className="inline-flex items-center gap-1.5 text-success"><span className="grid h-5 w-5 place-items-center rounded-full bg-success/10"><Check size={12}/></span>Meeting saved</li><li aria-current={!hasSummary?'step':undefined} className={`inline-flex items-center gap-1.5 ${!hasSummary?'text-accent':''}`}><span className={`grid h-5 w-5 place-items-center rounded-full ${!hasSummary?'bg-accent text-accent-foreground':'border border-border'}`}>{hasSummary&&!busy?<Check size={11}/>:2}</span>AI summary & actions</li><li aria-current={hasSummary&&!busy?'step':undefined} className={`inline-flex items-center gap-1.5 ${hasSummary&&!busy?'text-accent':''}`}><span className="grid h-5 w-5 place-items-center rounded-full border border-border">3</span>Meeting outcome</li></ol>
    {!hasSummary?<section className="rounded-[16px] border border-border bg-panel p-7 shadow-[var(--shadow-horizon)] sm:p-8" aria-labelledby="post-meeting-title"><div className="mb-5 inline-grid h-11 w-11 place-items-center rounded-[13px] bg-accent-soft text-accent">{busy?<Loader2 size={21} className="animate-spin motion-reduce:animate-none"/>:<FileCheck2 size={21}/>}</div><p className="horizon-eyebrow">{busy?'Your AI is at work':'The conversation is captured'}</p><h2 id="post-meeting-title" className="mt-2 text-[27px] font-semibold tracking-[-.035em] text-text">{busy?'Turning the conversation into clarity.':'Make the meeting useful.'}</h2><p className="mt-3 max-w-[610px] text-[13px] leading-6 text-2">{busy?props.getSummaryStatusMessage(summaryStatus):'One reviewed pass writes the summary, decisions and next steps together. No guessed tasks. No fragments pulled from the transcript.'}</p><div className="mt-6">{controls}</div><p className="mt-3 font-mono text-[9.5px] text-3">{providerDetail}</p>{!busy&&transcripts.length>0&&<div className="mt-6 border-t border-border pt-5"><label className="flex cursor-pointer items-start gap-3 text-[12px] text-text"><input type="checkbox" className="mt-0.5 h-4 w-4 accent-[var(--accent)]" checked={isAutoSummary} onChange={e=>{toggleIsAutoSummary(e.target.checked);try{localStorage.setItem(AUTO_SUMMARY_CHOICE_KEY,'chosen');setFirstChoice(false)}catch{}}}/><span><strong className="font-semibold">{firstChoice?'Make this automatic after future meetings':'Generate automatically after future meetings'}</strong><span className="mt-1 block max-w-[570px] text-[10.5px] leading-5 text-3">Approve your provider and included notes once. Changing provider, model, or destination requires a new approval.</span></span></label></div>}{!transcripts.length&&<p className="mt-5 text-[12px] text-2">No saved speech was found. Your notes remain available; no actions will be invented.</p>}</section>:<header className="space-y-3"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="horizon-eyebrow">{busy?'Updating your AI summary':'Ready to review'}</p><h2 className="mt-1 text-[24px] font-semibold tracking-[-.03em] text-text">Your meeting, made clear.</h2></div><span className="inline-flex items-center gap-1.5 rounded-full bg-accent-soft px-3 py-1.5 text-[10px] font-semibold text-accent"><Sparkles size={12}/>AI-generated · review before sharing</span></div><div className="flex flex-wrap items-center justify-between gap-3">{controls}<SummaryUpdaterButtonGroup isSaving={props.isSaving} isDirty={props.isTitleDirty||(summaryRef.current?.isDirty||false)} onSave={()=>props.onSaveAll().catch(()=>undefined)} onCopy={props.onCopySummary} onFind={()=>window.dispatchEvent(new CustomEvent('meetodds:find-summary'))} onOpenFolder={props.onOpenFolder} onExport={exportSummary} exportingFormat={exportingFormat} hasSummary/></div></header>}
    {summaryError&&<div role="alert" className="rounded-[12px] border border-border bg-panel p-4 text-[12px] leading-6 text-danger">{summaryError}</div>}{busy&&hasSummary&&<div role="status" className="flex items-center gap-3 rounded-[12px] border border-border bg-panel p-4 text-[12px] text-2"><Loader2 size={15} className="animate-spin"/>{props.getSummaryStatusMessage(summaryStatus)} Your previous result remains visible.</div>}{hasSummary&&!busy&&<MeetingOutcomeWorkspace meetingId={meeting.id}/>} {hasSummary&&<details className="overflow-hidden rounded-[16px] border border-border bg-panel"><summary className="cursor-pointer px-5 py-4 text-[12px] font-semibold text-text">Full AI summary <span className="ml-2 font-mono text-[9px] font-normal text-3">Generated with {providerDetail}</span></summary><div className="border-t border-border p-5" aria-busy={busy}><BlockNoteSummaryView key={meeting.id} ref={summaryRef} summaryData={aiSummary} onSave={props.onSaveSummary} onSummaryChange={props.onSummaryChange} onDirtyChange={props.onDirtyChange} status={summaryStatus} error={summaryError} onRegenerateSummary={()=>void generate(props.customPrompt)} meeting={{id:meeting.id,title:props.meetingTitle,created_at:meeting.created_at}}/></div></details>}
    <p className="pb-2 text-[10px] leading-5 text-3">{hasSummary?'Actions come from the saved AI summary. Confirmed decisions and completed work survive regeneration.':'Your saved transcript and notes are always available in the tabs above.'}</p>
  </div></div></div>;
}
