from pathlib import Path

p = Path('frontend/scripts/implement_streaming_live_subtitles.py')
text = p.read_text()
old = '''    old_call = dedent(''' + "'''" + '''\n                                // Transcribe with provider-agnostic approach\n                                match transcribe_chunk_with_provider(&engine_clone, chunk, &app_clone)\n                                    .await\n                                {\n    ''' + "'''" + ''')\n    new_call = dedent(''' + "'''" + '''\n                                // Canonical sentence decoding always has priority over speculative\n                                // subtitles. The preview worker observes this flag and yields.\n                                let preview_source = match &chunk.device_type {\n                                    crate::audio::recording_state::DeviceType::Microphone => "microphone",\n                                    crate::audio::recording_state::DeviceType::System => "system",\n                                };\n                                let transcription_result = {\n                                    let _canonical_guard = CanonicalTranscriptionGuard::new();\n                                    transcribe_chunk_with_provider(&engine_clone, chunk, &app_clone).await\n                                };\n                                let _ = app_clone.emit(\n                                    "live-transcript-preview-clear",\n                                    serde_json::json!({ "source": preview_source }),\n                                );\n\n                                match transcription_result {\n    ''' + "'''" + ''')\n    text = replace_once(text, old_call, new_call, "canonical priority wrapping")\n'''
new = '''    canonical_pattern = r'(?P<indent>[ \\t]*)// Transcribe with provider-agnostic approach\\n(?P=indent)match transcribe_chunk_with_provider\\(&engine_clone, chunk, &app_clone\\)\\n(?P=indent)[ \\t]*\\.await\\n(?P=indent)\\{'\n    canonical_replacement = r''' + "'''" + '''\\g<indent>// Canonical sentence decoding always has priority over speculative\n\\g<indent>// subtitles. The preview worker observes this flag and yields.\n\\g<indent>let preview_source = match &chunk.device_type {\n\\g<indent>    crate::audio::recording_state::DeviceType::Microphone => "microphone",\n\\g<indent>    crate::audio::recording_state::DeviceType::System => "system",\n\\g<indent>};\n\\g<indent>let transcription_result = {\n\\g<indent>    let _canonical_guard = CanonicalTranscriptionGuard::new();\n\\g<indent>    transcribe_chunk_with_provider(&engine_clone, chunk, &app_clone).await\n\\g<indent>};\n\\g<indent>let _ = app_clone.emit(\n\\g<indent>    "live-transcript-preview-clear",\n\\g<indent>    serde_json::json!({ "source": preview_source }),\n\\g<indent>);\n\n\\g<indent>match transcription_result {''' + "'''" + '''\n    text = regex_once(text, canonical_pattern, canonical_replacement, "canonical priority wrapping")\n'''
if old not in text:
    raise SystemExit('canonical block in implementation harness changed')
p.write_text(text.replace(old, new, 1))
