const { test } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const ts = require('typescript');
const vm = require('node:vm');
const root = path.resolve(__dirname, '../..');
const source = fs.readFileSync(path.join(root, 'src/lib/live-captions.ts'), 'utf8');
const js = ts.transpileModule(source, { compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2020 } }).outputText;
const exportsObject = {};
vm.runInNewContext(js, { exports: exportsObject });
const { resolveCaptionContent: resolve, fitCaptionGeometry: fit, normalizeCaptionAppearance: appearance, isCaptionFrame, selectCaptionScreen, readCaptionGeometry } = exportsObject;
const preview = { text: 'Buenos días a todos', source: 'microphone', speaker: 'me', speakerLabel: 'Me', revision: 3, audioStartTime: 1, audioEndTime: 3, latencyMs: 50 };
const translated = { segmentKey: 'live-preview-microphone', sourceText: preview.text, translatedText: 'Good morning everyone', targetLanguage: 'en', status: 'translated' };
test('translation disabled displays original speech', () => assert.equal(resolve({ preview, translationEnabled: false }).text, preview.text));
test('translation enabled displays English, never the original', () => assert.equal(resolve({ preview, translation: translated, translationEnabled: true }).text, translated.translatedText));
test('pending translation never leaks original speech', () => { const r = resolve({ preview, translationEnabled: true }); assert.equal(r.text, ''); assert.equal(r.phase, 'translating'); });
test('streaming target words are displayed immediately', () => assert.equal(resolve({ preview, translationEnabled: true, translation: { ...translated, translatedText: 'Good morning', status: 'translating' } }).text, 'Good morning'));
test('changing language rejects previous English result', () => { const r = resolve({ preview, translationEnabled: true, translation: translated, targetLanguage: 'th' }); assert.equal(r.text, ''); assert.equal(r.language, 'th'); });
test('selected target is honored', () => assert.equal(resolve({ preview, translationEnabled: true, translation: { ...translated, targetLanguage: 'fr', translatedText: 'Bonjour' }, targetLanguage: 'fr' }).text, 'Bonjour'));
test('failed translation without prior output is a quiet error state', () => { const r = resolve({ preview, translationEnabled: true, translation: { ...translated, translatedText: undefined, status: 'error' } }); assert.equal(r.phase, 'error'); assert.equal(r.text, ''); });
test('failed revision preserves the last translated phrase while recovering', () => { const r = resolve({ preview, translationEnabled: true, translation: { ...translated, status: 'error', error: 'timeout' } }); assert.equal(r.phase, 'recovering'); assert.equal(r.text, 'Good morning everyone'); assert.notEqual(r.text, preview.text); });
test('pause does not display stale words', () => { const r = resolve({ preview, translationEnabled: true, translation: translated, isPaused: true }); assert.equal(r.text, ''); assert.equal(r.phase, 'paused'); });
test('no speech means listening, not a false translating state', () => assert.equal(resolve({ preview: null, translationEnabled: true }).phase, 'listening'));
test('restores a safe default position', () => { const r = fit(null, { x: 0, y: 0, width: 1440, height: 900 }); assert.equal(r.width, 720); assert.equal(r.x, 360); assert.ok(r.y > 500); });
test('offscreen and oversized windows are clamped', () => { const r = fit({ x: 9000, y: -8000, width: 9000, height: 9000 }, { x: 0, y: 0, width: 1280, height: 800 }); assert.ok(r.x >= 0 && r.y >= 0); assert.ok(r.x + r.width <= 1280 && r.y + r.height <= 800); });
test('negative monitor coordinates are supported', () => { const screen = { x: -1920, y: -200, width: 1920, height: 1080 }; const r = fit({ x: -1200, y: 100, width: 600, height: 200 }, screen); assert.equal(r.x, -1200); assert.equal(r.y, 100); });
test('disconnected monitor falls back to an available monitor', () => { const screen = { x: 0, y: 0, width: 1440, height: 900 }; assert.equal(selectCaptionScreen({ x: -1200, y: 100 }, [screen]), screen); });
test('preserves the selected secondary display', () => { const screens = [{ x: 0, y: 0, width: 1440, height: 900 }, { x: -1920, y: 0, width: 1920, height: 1080 }]; assert.equal(selectCaptionScreen({ x: -1200, y: 100 }, screens), screens[1]); });
test('invalid stored dimensions fall back safely', () => { const r = fit({ width: NaN, height: Infinity, x: NaN, y: Infinity }, { x: 0, y: 0, width: 1440, height: 900 }); assert.equal(r.width, 720); assert.equal(r.height, 210); assert.ok(Number.isFinite(r.x)); });
test('corrupt storage does not break window creation', () => assert.equal(readCaptionGeometry({ getItem: () => '{' }), null));
test('storage denial does not break window creation', () => assert.equal(readCaptionGeometry({ getItem: () => { throw Error('denied'); } }), null));
test('font size and opacity have accessible safe limits', () => { const r = appearance({ fontSize: 1000, opacity: -1 }); assert.equal(r.fontSize, 40); assert.equal(r.opacity, .35); });
test('frame validation rejects malformed or unbounded payloads', () => { assert.equal(isCaptionFrame(null), false); assert.equal(isCaptionFrame({ text: 'x' }), false); const f = { ...resolve({ preview, translationEnabled: false }), epoch: 'run1', sessionId: 's1', enabled: true, sequence: 0 }; assert.equal(isCaptionFrame(f), true); assert.equal(isCaptionFrame({ ...f, sequence: NaN }), false); assert.equal(isCaptionFrame({ ...f, text: 'x'.repeat(10001) }), false); });
const { sameCaptionUtterance, CaptionFrameGate } = exportsObject;
test('revised overlapping speech belongs to the same caption turn', () => assert.equal(sameCaptionUtterance(preview, { ...preview, revision: 4, audioEndTime: 4 }), true));
test('different speakers and nonoverlapping turns never reuse a translation', () => { assert.equal(sameCaptionUtterance(preview, { ...preview, source: 'system' }), false); assert.equal(sameCaptionUtterance(preview, { ...preview, audioStartTime: 3, audioEndTime: 4 }), false); assert.equal(sameCaptionUtterance(preview, null), false); });
const frame = (sequence, patch = {}) => ({ ...resolve({ preview, translationEnabled: false }), sessionId: 's1', epoch: 'e1', sequence, enabled: true, ...patch });
test('late IPC frames cannot replace newer caption text', () => { const g = new CaptionFrameGate(); assert.ok(g.accept(frame(3))); assert.equal(g.accept(frame(2)), null); assert.equal(g.accept(frame(3)), null); });
test('a dismissed window stays hidden while old enabled frames arrive', () => { const g = new CaptionFrameGate(); g.accept(frame(1)); g.dismiss(); const r = g.accept(frame(2)); assert.equal(r.enabled, false); assert.equal(r.text, ''); });
test('owner acknowledgement allows an explicit reopening', () => { const g = new CaptionFrameGate(); g.accept(frame(1)); g.dismiss(); g.accept(frame(2, { enabled: false })); assert.equal(g.accept(frame(3)).enabled, true); });
test('a reloaded main window retires its previous IPC epoch', () => { const g = new CaptionFrameGate(); g.accept(frame(8)); assert.ok(g.accept(frame(1, { epoch: 'e2' }))); assert.equal(g.accept(frame(9)), null); });
test('mixed-DPI placement uses physical positions with logical sizes', () => { const r = fit(null, { x: 1920, y: 0, width: 2880, height: 1800, scaleFactor: 2 }); assert.equal(r.width, 720); assert.equal(r.x, 2640); assert.ok(r.x + r.width * 2 <= 4800); assert.ok(r.y + r.height * 2 <= 1800); });
