#!/usr/bin/env python3
"""Generate frontend/src-tauri/src/languages/scenes.rs from authored JSON."""
import json, pathlib, sys

ORDER = ["nb", "en", "fr", "de", "it", "pt", "zh", "hi"]
NAMES = {"nb":"NORWEGIAN","en":"ENGLISH","fr":"FRENCH","de":"GERMAN",
         "it":"ITALIAN","pt":"PORTUGUESE","zh":"MANDARIN","hi":"HINDI"}

def rs(s: str) -> str:
    """Rust string literal. Content is prose; escape only what Rust requires."""
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'

HEADER = '''//! Conversation scenes for every target language except Spanish.
//!
//! Spanish keeps its own set in `crate::spanish::scenes` and is deliberately
//! untouched by this module; the two are structurally identical, and unifying
//! them is a follow-up once the Spanish engine is parameterised by language.
//!
//! GENERATED FILE — do not hand-edit. Content was authored per language against
//! the shared scene skeleton (fixed English metadata, per-language dialogue) and
//! regenerated by tools/scene-authoring. The English fields (`id`, `tutor_role`,
//! `learner_role`, `goal`, and each beat's `goal`) are identical across every
//! language on purpose: they key the tutor's deterministic progression.
//!
//! Content status: machine-authored and checked for structure, register
//! consistency and orthography. NOT yet reviewed by a fluent speaker of each
//! language — see docs/SCENE-AUTHORING.md before making teaching claims.

/// One stage of a scene. `max_turns` matches the Spanish engine's pacing.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Beat {
    pub goal: &'static str,
    pub opener: &'static str,
    pub options: &'static str,
    pub max_turns: usize,
}

/// A role-play situation, four beats long.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Scene {
    pub id: &'static str,
    pub tutor_role: &'static str,
    pub learner_role: &'static str,
    pub goal: &'static str,
    pub beats: [Beat; 4],
    /// Indexed by the tutor's level dial: 0 beginner, 1 intermediate, 2 advanced.
    pub target_structures: [[&'static str; 2]; 3],
    pub filler: &'static str,
}

impl Scene {
    pub fn beat(&self, index: usize) -> &Beat {
        &self.beats[index.min(self.beats.len() - 1)]
    }
    pub fn targets(&self, dial: u8) -> &[&'static str; 2] {
        &self.target_structures[(dial.min(2)) as usize]
    }
}

const fn beat(goal: &'static str, opener: &'static str, options: &'static str) -> Beat {
    Beat { goal, opener, options, max_turns: 3 }
}

/// Scene ids, in the order every language presents them.
pub static SCENE_IDS: [&str; 8] = [
    "ordering_food", "meeting_someone", "school_day", "weekend_plans",
    "shopping", "asking_directions", "hotel_checkin", "planning_party",
];

'''

def scene_rs(s):
    beats = ",\n".join(
        f"            beat({rs(b['goal'])}, {rs(b['opener'])}, {rs(b['options'])})"
        for b in s["beats"])
    ts = ",\n".join(
        "            [" + ", ".join(rs(c) for c in row) + "]"
        for row in s["target_structures"])
    return (f"    Scene {{\n"
            f"        id: {rs(s['id'])},\n"
            f"        tutor_role: {rs(s['tutor_role'])},\n"
            f"        learner_role: {rs(s['learner_role'])},\n"
            f"        goal: {rs(s['goal'])},\n"
            f"        filler: {rs(s['filler'])},\n"
            f"        beats: [\n{beats},\n        ],\n"
            f"        target_structures: [\n{ts},\n        ],\n"
            f"    }}")

def main(src_dir, out_path):
    out = [HEADER]
    for lid in ORDER:
        d = json.loads((pathlib.Path(src_dir) / f"{lid}.json").read_text(encoding="utf-8"))
        const = f"{NAMES[lid]}_SCENES"
        body = ",\n".join(scene_rs(s) for s in d["scenes"])
        out.append(f"pub static {const}: [Scene; 8] = [\n{body},\n];\n")
    lookup = "\n".join(
        f'        "{lid}" => Some(&{NAMES[lid]}_SCENES),' for lid in ORDER)
    out.append(f'''/// Scenes for a language id. Spanish (`"es"`) is served by
/// `crate::spanish::scenes` and returns `None` here.
pub fn scenes_for(language_id: &str) -> Option<&'static [Scene; 8]> {{
    match language_id {{
{lookup}
        _ => None,
    }}
}}

/// Language ids this module carries scenes for.
pub static SCENE_LANGUAGES: [&str; {len(ORDER)}] = [{", ".join(f'"{l}"' for l in ORDER)}];
''')
    out.append(TESTS)
    pathlib.Path(out_path).write_text("\n".join(out), encoding="utf-8")
    print(f"wrote {out_path} ({len(''.join(out).splitlines())} lines)")


TESTS = r'''
#[cfg(test)]
mod tests {
    use super::*;

    fn all_sets() -> Vec<(&'static str, &'static [Scene; 8])> {
        SCENE_LANGUAGES
            .iter()
            .map(|id| (*id, scenes_for(id).expect("registered language has scenes")))
            .collect()
    }

    #[test]
    fn every_language_has_eight_scenes_in_the_shared_order() {
        for (lang, scenes) in all_sets() {
            assert_eq!(scenes.len(), 8, "{lang}");
            for (scene, want) in scenes.iter().zip(SCENE_IDS.iter()) {
                assert_eq!(&scene.id, want, "{lang} scene order");
            }
        }
    }

    #[test]
    fn beats_are_complete_and_paced() {
        for (lang, scenes) in all_sets() {
            for scene in scenes.iter() {
                assert_eq!(scene.beats.len(), 4, "{lang}/{}", scene.id);
                for beat in scene.beats.iter() {
                    assert!(beat.max_turns > 0, "{lang}/{}", scene.id);
                    assert!(!beat.goal.is_empty(), "{lang}/{}", scene.id);
                    assert!(!beat.opener.trim().is_empty(), "{lang}/{}", scene.id);
                    assert!(!beat.options.trim().is_empty(), "{lang}/{}", scene.id);
                }
            }
        }
    }

    /// Mirrors the invariant `spanish::scenes` asserts. Mandarin writes the
    /// full-width form, so both are accepted.
    #[test]
    fn openers_and_options_are_questions() {
        for (lang, scenes) in all_sets() {
            for scene in scenes.iter() {
                for beat in scene.beats.iter() {
                    for (field, text) in [("opener", beat.opener), ("options", beat.options)] {
                        assert!(
                            text.ends_with('?') || text.ends_with('？'),
                            "{lang}/{}/{field} must end with a question mark: {text}",
                            scene.id
                        );
                    }
                }
            }
        }
    }

    #[test]
    fn target_structures_cover_every_dial_position() {
        for (lang, scenes) in all_sets() {
            for scene in scenes.iter() {
                for dial in 0u8..=2 {
                    let row = scene.targets(dial);
                    for cell in row.iter() {
                        assert!(!cell.trim().is_empty(), "{lang}/{} dial {dial}", scene.id);
                    }
                }
                // Out-of-range dials clamp rather than panicking.
                assert_eq!(scene.targets(9), scene.targets(2), "{lang}/{}", scene.id);
            }
        }
    }

    /// The English metadata keys the tutor's deterministic progression, so it
    /// must be identical in every language. A translated `goal` would silently
    /// desynchronise that language from the engine.
    #[test]
    fn english_metadata_is_identical_across_languages() {
        let reference = scenes_for(SCENE_LANGUAGES[0]).unwrap();
        for (lang, scenes) in all_sets() {
            for (scene, base) in scenes.iter().zip(reference.iter()) {
                assert_eq!(scene.id, base.id, "{lang}");
                assert_eq!(scene.tutor_role, base.tutor_role, "{lang}/{}", scene.id);
                assert_eq!(scene.learner_role, base.learner_role, "{lang}/{}", scene.id);
                assert_eq!(scene.goal, base.goal, "{lang}/{}", scene.id);
                for (beat, bbase) in scene.beats.iter().zip(base.beats.iter()) {
                    assert_eq!(beat.goal, bbase.goal, "{lang}/{}", scene.id);
                }
                // The advanced row is a shared English label set.
                assert_eq!(
                    scene.target_structures[2], base.target_structures[2],
                    "{lang}/{}", scene.id
                );
            }
        }
    }

    /// Dialogue must actually differ per language; identical openers would mean
    /// a language was left untranslated.
    #[test]
    fn dialogue_is_distinct_per_language() {
        let sets = all_sets();
        for (i, (lang_a, a)) in sets.iter().enumerate() {
            for (lang_b, b) in sets.iter().skip(i + 1) {
                let shared = a
                    .iter()
                    .zip(b.iter())
                    .filter(|(x, y)| x.beats[0].opener == y.beats[0].opener)
                    .count();
                assert_eq!(shared, 0, "{lang_a} and {lang_b} share opening lines");
            }
        }
    }

    #[test]
    fn fillers_are_present_and_reused_not_unique_per_scene() {
        for (lang, scenes) in all_sets() {
            let mut distinct = std::collections::HashSet::new();
            for scene in scenes.iter() {
                assert!(!scene.filler.trim().is_empty(), "{lang}/{}", scene.id);
                distinct.insert(scene.filler);
            }
            assert!(distinct.len() <= 5, "{lang} has {} fillers", distinct.len());
        }
    }

    #[test]
    fn spanish_is_not_served_here() {
        // Spanish keeps its own untouched set in crate::spanish::scenes.
        assert!(scenes_for("es").is_none());
        assert!(scenes_for("xx").is_none());
        assert!(!SCENE_LANGUAGES.contains(&"es"));
    }

    #[test]
    fn mandarin_content_carries_no_pinyin() {
        let zh = scenes_for("zh").unwrap();
        for scene in zh.iter() {
            for beat in scene.beats.iter() {
                for text in [beat.opener, beat.options] {
                    let latin: String = text.chars().filter(|c| c.is_ascii_alphabetic()).collect();
                    assert!(
                        latin.is_empty(),
                        "Mandarin {} contains Latin letters: {text}",
                        scene.id
                    );
                }
            }
        }
    }

    #[test]
    fn beat_lookup_clamps_past_the_last_beat() {
        let scenes = scenes_for("de").unwrap();
        let scene = &scenes[0];
        assert_eq!(scene.beat(0).goal, scene.beats[0].goal);
        assert_eq!(scene.beat(99).goal, scene.beats[3].goal);
    }

    /// Hindi is taught in Roman script by design (docs/SCENE-AUTHORING.md):
    /// learners speak it and never read Devanagari, so no learner-facing
    /// string may contain a Devanagari codepoint (U+0900..=U+097F) or an IAST
    /// diacritic. Plain ASCII letters only.
    #[test]
    fn hindi_content_is_roman_script_only() {
        let hi = scenes_for("hi").unwrap();
        for scene in hi.iter() {
            let mut texts = vec![scene.filler];
            for beat in scene.beats.iter() {
                texts.push(beat.opener);
                texts.push(beat.options);
            }
            for row in &scene.target_structures[..2] {
                texts.extend(row.iter().copied());
            }
            for text in texts {
                assert!(
                    !text.chars().any(|c| ('\u{0900}'..='\u{097F}').contains(&c)),
                    "Hindi {} contains Devanagari: {text}",
                    scene.id
                );
                assert!(
                    text.chars().filter(|c| c.is_alphabetic()).all(|c| c.is_ascii()),
                    "Hindi {} contains a non-ASCII letter (IAST diacritic?): {text}",
                    scene.id
                );
            }
        }
    }

    /// Service scenes address the learner as aap, peer scenes as tum, and no
    /// scene mixes the two. tu is never modelled.
    #[test]
    fn hindi_register_is_split_by_scene_and_never_mixed() {
        let hi = scenes_for("hi").unwrap();
        let service = ["ordering_food", "shopping", "hotel_checkin", "asking_directions"];
        let aap = ["aap", "aapko", "aapka", "aapki", "aapke", "aapne"];
        let tum = ["tum", "tumhe", "tumhara", "tumhari", "tumhare", "tumne"];
        let words = |text: &str| -> Vec<String> {
            text.split(|c: char| !c.is_alphanumeric())
                .filter(|w| !w.is_empty())
                .map(|w| w.to_lowercase())
                .collect()
        };
        for scene in hi.iter() {
            let mut has_aap = false;
            let mut has_tum = false;
            for beat in scene.beats.iter() {
                for text in [beat.opener, beat.options] {
                    for w in words(text) {
                        assert_ne!(w, "tu", "Hindi {} models tu: {text}", scene.id);
                        has_aap |= aap.contains(&w.as_str());
                        has_tum |= tum.contains(&w.as_str());
                    }
                }
            }
            assert!(!(has_aap && has_tum), "Hindi {} mixes aap and tum", scene.id);
            if service.contains(&scene.id) {
                assert!(has_aap && !has_tum, "Hindi service scene {} should use aap", scene.id);
            } else {
                assert!(has_tum && !has_aap, "Hindi peer scene {} should use tum", scene.id);
            }
        }
    }
}
'''

if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2])
